/* Quick Cheat — reference tables for Tenses, Particles, Persons,
   Question words, Confusing pairs, Counters. Globals (CHEAT) read
   by buildCheat() in app.js.

   Structure: each section has `sets`, where EACH set contains the
   FULL list of items with example sentences in a specific context
   (Daily / Workplace / Restaurant / Travel / Study).
   Switch sets via the dot navigator to see the same item used in
   different real-world situations. */
const CHEAT = {
  // ════════════════════════════════════════════════════════════════
  // TENSES — 5 verbs, each fully conjugated (covers all 3 verb groups)
  // ════════════════════════════════════════════════════════════════
  tenses: {
    intro: "Same conjugation pattern, five different verbs. Click any dot below to switch — together they cover all three verb groups (ichidan, godan, irregular). Click any Japanese cell to hear it.",
    sets: [
      {
        label: "1", verb: "食べる", verbRo: "taberu", group: "ichidan (-eru)", meaning: "to eat",
        rows: [
          { tense: "Present (positive)",  polite: "食べます",         politeRo: "tabemasu",         plain: "食べる",       plainRo: "taberu",      copula: "です",                 copulaRo: "desu",                 example: "パンを食べます",          exampleRo: "pan o tabemasu",                ne: "रोटी खान्छु" },
          { tense: "Present (negative)",  polite: "食べません",       politeRo: "tabemasen",        plain: "食べない",     plainRo: "tabenai",     copula: "じゃありません",       copulaRo: "ja arimasen",          example: "肉を食べません",          exampleRo: "niku o tabemasen",              ne: "मासु खाँदिनँ" },
          { tense: "Past (positive)",     polite: "食べました",       politeRo: "tabemashita",      plain: "食べた",       plainRo: "tabeta",      copula: "でした",               copulaRo: "deshita",              example: "朝、パンを食べました",    exampleRo: "asa, pan o tabemashita",        ne: "बिहान रोटी खाएँ" },
          { tense: "Past (negative)",     polite: "食べませんでした", politeRo: "tabemasen deshita", plain: "食べなかった", plainRo: "tabenakatta", copula: "じゃありませんでした", copulaRo: "ja arimasen deshita",  example: "昨日、肉を食べませんでした", exampleRo: "kinō, niku o tabemasen deshita", ne: "हिजो मासु खाइनँ" },
          { tense: "Te-form (connector)", polite: "食べて",           politeRo: "tabete",           plain: "食べて",       plainRo: "tabete",      copula: "で",                   copulaRo: "de",                   example: "食べて、行きます",        exampleRo: "tabete, ikimasu",               ne: "खाएर जान्छु" },
          { tense: "Tai (want to)",       polite: "食べたいです",     politeRo: "tabetai desu",     plain: "食べたい",     plainRo: "tabetai",     copula: "—",                    copulaRo: "",                     example: "すしを食べたいです",      exampleRo: "sushi o tabetai desu",          ne: "सुसी खान मन छ" },
          { tense: "Volitional (let's)",  polite: "食べましょう",     politeRo: "tabemashō",        plain: "食べよう",     plainRo: "tabeyō",      copula: "—",                    copulaRo: "",                     example: "一緒に食べましょう",      exampleRo: "issho ni tabemashō",            ne: "सँगै खाऔं" },
          { tense: "Te-iru (-ing/now)",   polite: "食べています",     politeRo: "tabete imasu",     plain: "食べている",   plainRo: "tabete iru",  copula: "—",                    copulaRo: "",                     example: "今、食べています",        exampleRo: "ima, tabete imasu",             ne: "अहिले खाइरहेको छु" },
          { tense: "Can do (potential)",  polite: "食べられます",     politeRo: "taberaremasu",     plain: "食べられる",   plainRo: "taberareru",  copula: "—",                    copulaRo: "",                     example: "辛い物が食べられます",    exampleRo: "karai mono ga taberaremasu",    ne: "पिरो खान सक्छु" },
        ],
      },
      {
        label: "2", verb: "飲む", verbRo: "nomu", group: "godan (-mu)", meaning: "to drink",
        rows: [
          { tense: "Present (positive)",  polite: "飲みます",         politeRo: "nomimasu",         plain: "飲む",       plainRo: "nomu",       copula: "です",                 copulaRo: "desu",                example: "水を飲みます",            exampleRo: "mizu o nomimasu",                 ne: "पानी पिउँछु" },
          { tense: "Present (negative)",  polite: "飲みません",       politeRo: "nomimasen",        plain: "飲まない",   plainRo: "nomanai",    copula: "じゃありません",       copulaRo: "ja arimasen",         example: "お酒を飲みません",        exampleRo: "osake o nomimasen",               ne: "रक्सी पिउँदिनँ" },
          { tense: "Past (positive)",     polite: "飲みました",       politeRo: "nomimashita",      plain: "飲んだ",     plainRo: "nonda",      copula: "でした",               copulaRo: "deshita",             example: "コーヒーを飲みました",    exampleRo: "kōhī o nomimashita",              ne: "कफी पिएँ" },
          { tense: "Past (negative)",     polite: "飲みませんでした", politeRo: "nomimasen deshita", plain: "飲まなかった", plainRo: "nomanakatta", copula: "じゃありませんでした", copulaRo: "ja arimasen deshita", example: "昨日、お酒を飲みませんでした", exampleRo: "kinō, osake o nomimasen deshita", ne: "हिजो रक्सी पिइनँ" },
          { tense: "Te-form (connector)", polite: "飲んで",           politeRo: "nonde",            plain: "飲んで",     plainRo: "nonde",      copula: "で",                   copulaRo: "de",                  example: "水を飲んで、寝ます",      exampleRo: "mizu o nonde, nemasu",            ne: "पानी पिएर सुत्छु" },
          { tense: "Tai (want to)",       polite: "飲みたいです",     politeRo: "nomitai desu",     plain: "飲みたい",   plainRo: "nomitai",    copula: "—",                    copulaRo: "",                    example: "ビールを飲みたいです",    exampleRo: "bīru o nomitai desu",             ne: "बियर पिउन मन छ" },
          { tense: "Volitional (let's)",  polite: "飲みましょう",     politeRo: "nomimashō",        plain: "飲もう",     plainRo: "nomō",       copula: "—",                    copulaRo: "",                    example: "一緒に飲みましょう",      exampleRo: "issho ni nomimashō",              ne: "सँगै पिऔं" },
          { tense: "Te-iru (-ing/now)",   polite: "飲んでいます",     politeRo: "nonde imasu",      plain: "飲んでいる", plainRo: "nonde iru",  copula: "—",                    copulaRo: "",                    example: "今、お茶を飲んでいます",  exampleRo: "ima, ocha o nonde imasu",         ne: "अहिले चिया पिइरहेको छु" },
          { tense: "Can do (potential)",  polite: "飲めます",         politeRo: "nomemasu",         plain: "飲める",     plainRo: "nomeru",     copula: "—",                    copulaRo: "",                    example: "ビールが飲めます",        exampleRo: "bīru ga nomemasu",                ne: "बियर पिउन सक्छु" },
        ],
      },
      {
        label: "3", verb: "行く", verbRo: "iku", group: "godan (-ku, irregular te-form)", meaning: "to go",
        rows: [
          { tense: "Present (positive)",  polite: "行きます",         politeRo: "ikimasu",          plain: "行く",       plainRo: "iku",        copula: "です",                 copulaRo: "desu",                example: "学校に行きます",          exampleRo: "gakkō ni ikimasu",                ne: "स्कूल जान्छु" },
          { tense: "Present (negative)",  polite: "行きません",       politeRo: "ikimasen",         plain: "行かない",   plainRo: "ikanai",     copula: "じゃありません",       copulaRo: "ja arimasen",         example: "今日、会社に行きません", exampleRo: "kyō, kaisha ni ikimasen",         ne: "आज अफिस जान्दिनँ" },
          { tense: "Past (positive)",     polite: "行きました",       politeRo: "ikimashita",       plain: "行った",     plainRo: "itta",       copula: "でした",               copulaRo: "deshita",             example: "昨日、東京に行きました",  exampleRo: "kinō, tōkyō ni ikimashita",       ne: "हिजो टोकियो गएँ" },
          { tense: "Past (negative)",     polite: "行きませんでした", politeRo: "ikimasen deshita", plain: "行かなかった", plainRo: "ikanakatta", copula: "じゃありませんでした", copulaRo: "ja arimasen deshita", example: "昨日、どこにも行きませんでした", exampleRo: "kinō, doko ni mo ikimasen deshita", ne: "हिजो कहीं गइनँ" },
          { tense: "Te-form (connector)", polite: "行って",           politeRo: "itte",             plain: "行って",     plainRo: "itte",       copula: "で",                   copulaRo: "de",                  example: "学校に行って、勉強します", exampleRo: "gakkō ni itte, benkyō shimasu",   ne: "स्कूल गएर पढ्छु" },
          { tense: "Tai (want to)",       polite: "行きたいです",     politeRo: "ikitai desu",      plain: "行きたい",   plainRo: "ikitai",     copula: "—",                    copulaRo: "",                    example: "日本に行きたいです",      exampleRo: "nihon ni ikitai desu",            ne: "जापान जान मन छ" },
          { tense: "Volitional (let's)",  polite: "行きましょう",     politeRo: "ikimashō",         plain: "行こう",     plainRo: "ikō",        copula: "—",                    copulaRo: "",                    example: "一緒に行きましょう",      exampleRo: "issho ni ikimashō",               ne: "सँगै जाऔं" },
          { tense: "Te-iru (-ing/now)",   polite: "行っています",     politeRo: "itte imasu",       plain: "行っている", plainRo: "itte iru",   copula: "—",                    copulaRo: "",                    example: "毎日、学校に行っています", exampleRo: "mainichi, gakkō ni itte imasu",   ne: "हरेक दिन स्कूल जान्छु" },
          { tense: "Can do (potential)",  polite: "行けます",         politeRo: "ikemasu",          plain: "行ける",     plainRo: "ikeru",      copula: "—",                    copulaRo: "",                    example: "明日、行けます",          exampleRo: "ashita, ikemasu",                 ne: "भोलि जान सक्छु" },
        ],
      },
      {
        label: "4", verb: "する", verbRo: "suru", group: "irregular", meaning: "to do",
        rows: [
          { tense: "Present (positive)",  polite: "します",           politeRo: "shimasu",          plain: "する",       plainRo: "suru",       copula: "です",                 copulaRo: "desu",                example: "仕事をします",            exampleRo: "shigoto o shimasu",               ne: "काम गर्छु" },
          { tense: "Present (negative)",  polite: "しません",         politeRo: "shimasen",         plain: "しない",     plainRo: "shinai",     copula: "じゃありません",       copulaRo: "ja arimasen",         example: "テレビを見ません",        exampleRo: "terebi o mimasen",                ne: "टीभी हेर्दिनँ" },
          { tense: "Past (positive)",     polite: "しました",         politeRo: "shimashita",       plain: "した",       plainRo: "shita",      copula: "でした",               copulaRo: "deshita",             example: "宿題をしました",          exampleRo: "shukudai o shimashita",           ne: "गृहकार्य गरें" },
          { tense: "Past (negative)",     polite: "しませんでした",   politeRo: "shimasen deshita", plain: "しなかった", plainRo: "shinakatta", copula: "じゃありませんでした", copulaRo: "ja arimasen deshita", example: "昨日、何もしませんでした", exampleRo: "kinō, nani mo shimasen deshita",  ne: "हिजो केहि गरिनँ" },
          { tense: "Te-form (connector)", polite: "して",             politeRo: "shite",            plain: "して",       plainRo: "shite",      copula: "で",                   copulaRo: "de",                  example: "宿題をして、寝ます",      exampleRo: "shukudai o shite, nemasu",        ne: "गृहकार्य गरेर सुत्छु" },
          { tense: "Tai (want to)",       polite: "したいです",       politeRo: "shitai desu",      plain: "したい",     plainRo: "shitai",     copula: "—",                    copulaRo: "",                    example: "旅行をしたいです",        exampleRo: "ryokō o shitai desu",             ne: "यात्रा गर्न मन छ" },
          { tense: "Volitional (let's)",  polite: "しましょう",       politeRo: "shimashō",         plain: "しよう",     plainRo: "shiyō",      copula: "—",                    copulaRo: "",                    example: "一緒に勉強しましょう",    exampleRo: "issho ni benkyō shimashō",        ne: "सँगै पढौं" },
          { tense: "Te-iru (-ing/now)",   polite: "しています",       politeRo: "shite imasu",      plain: "している",   plainRo: "shite iru",  copula: "—",                    copulaRo: "",                    example: "今、宿題をしています",    exampleRo: "ima, shukudai o shite imasu",     ne: "अहिले गृहकार्य गर्दैछु" },
          { tense: "Can do (potential)",  polite: "できます",         politeRo: "dekimasu",         plain: "できる",     plainRo: "dekiru",     copula: "—",                    copulaRo: "",                    example: "日本語ができます",        exampleRo: "nihongo ga dekimasu",             ne: "जापानी आउँछ" },
        ],
      },
      {
        label: "5", verb: "来る", verbRo: "kuru", group: "irregular", meaning: "to come",
        rows: [
          { tense: "Present (positive)",  polite: "来ます",           politeRo: "kimasu",           plain: "来る",       plainRo: "kuru",       copula: "です",                 copulaRo: "desu",                example: "友達が来ます",            exampleRo: "tomodachi ga kimasu",             ne: "साथी आउँछ" },
          { tense: "Present (negative)",  polite: "来ません",         politeRo: "kimasen",          plain: "来ない",     plainRo: "konai",      copula: "じゃありません",       copulaRo: "ja arimasen",         example: "明日、彼は来ません",      exampleRo: "ashita, kare wa kimasen",         ne: "भोलि ऊ आउँदैन" },
          { tense: "Past (positive)",     polite: "来ました",         politeRo: "kimashita",        plain: "来た",       plainRo: "kita",       copula: "でした",               copulaRo: "deshita",             example: "昨日、友達が来ました",    exampleRo: "kinō, tomodachi ga kimashita",    ne: "हिजो साथी आयो" },
          { tense: "Past (negative)",     polite: "来ませんでした",   politeRo: "kimasen deshita",  plain: "来なかった", plainRo: "konakatta",  copula: "じゃありませんでした", copulaRo: "ja arimasen deshita", example: "昨日、誰も来ませんでした", exampleRo: "kinō, dare mo kimasen deshita",   ne: "हिजो कोही आएन" },
          { tense: "Te-form (connector)", polite: "来て",             politeRo: "kite",             plain: "来て",       plainRo: "kite",       copula: "で",                   copulaRo: "de",                  example: "家に来て、食べました",    exampleRo: "ie ni kite, tabemashita",         ne: "घरमा आएर खाएँ" },
          { tense: "Tai (want to)",       polite: "来たいです",       politeRo: "kitai desu",       plain: "来たい",     plainRo: "kitai",      copula: "—",                    copulaRo: "",                    example: "また日本に来たいです",    exampleRo: "mata nihon ni kitai desu",        ne: "फेरि जापान आउन मन छ" },
          { tense: "Volitional (let's)",  polite: "来ましょう",       politeRo: "kimashō",          plain: "来よう",     plainRo: "koyō",       copula: "—",                    copulaRo: "",                    example: "また来ましょう",          exampleRo: "mata kimashō",                    ne: "फेरि आऔं" },
          { tense: "Te-iru (-ing/now)",   polite: "来ています",       politeRo: "kite imasu",       plain: "来ている",   plainRo: "kite iru",   copula: "—",                    copulaRo: "",                    example: "もう来ています",          exampleRo: "mō kite imasu",                   ne: "अहिले आइसकेको छ" },
          { tense: "Can do (potential)",  polite: "来られます",       politeRo: "koraremasu",       plain: "来られる",   plainRo: "korareru",   copula: "—",                    copulaRo: "",                    example: "明日、来られます",        exampleRo: "ashita, koraremasu",              ne: "भोलि आउन सक्छु" },
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // PARTICLES — same 16 particles, 5 example contexts
  // ════════════════════════════════════════════════════════════════
  particles: {
    intro: "All 16 essential particles, in 5 contexts. Same particle, fresh example — see how each one looks across daily life, work, restaurants, travel, and study.",
    sets: [
      {
        label: "1", title: "Daily life",
        rows: [
          { p: "は", ro: "wa",   role: "Topic marker",        ex: "私は学生です",         exRo: "watashi wa gakusei desu",  exNe: "म विद्यार्थी हुँ",   note: "Sets what we're talking ABOUT. Pronounced 'wa'." },
          { p: "が", ro: "ga",   role: "Subject / new info",  ex: "猫がいます",           exRo: "neko ga imasu",            exNe: "बिरालो छ",          note: "Marks who DID it or new info. Use after 誰/何." },
          { p: "を", ro: "o",    role: "Direct object",       ex: "水を飲みます",         exRo: "mizu o nomimasu",          exNe: "पानी पिउँछु",       note: "Marks WHAT the verb acts on." },
          { p: "の", ro: "no",   role: "Possessive / linker", ex: "私の本",              exRo: "watashi no hon",           exNe: "मेरो किताब",        note: "A の B = A's B." },
          { p: "に", ro: "ni",   role: "Target / time",       ex: "公園に行きます",       exRo: "kōen ni ikimasu",          exNe: "पार्क जान्छु",      note: "Destination / time point / indirect object." },
          { p: "で", ro: "de",   role: "Location of action",  ex: "家で食べます",         exRo: "ie de tabemasu",           exNe: "घरमा खान्छु",       note: "Where ACTION happens; also means / by." },
          { p: "へ", ro: "e",    role: "Direction",           ex: "東京へ行きます",       exRo: "tōkyō e ikimasu",          exNe: "टोकियो तिर जान्छु",  note: "Toward a place. Often = に." },
          { p: "と", ro: "to",   role: "With / and",          ex: "友達と話します",       exRo: "tomodachi to hanashimasu", exNe: "साथीसँग कुरा गर्छु",  note: "Companion or complete-list 'and'." },
          { p: "や", ro: "ya",   role: "And (open list)",     ex: "りんごやバナナ",       exRo: "ringo ya banana",          exNe: "स्याउ, केरा, आदि",   note: "A, B, and others — non-exhaustive." },
          { p: "も", ro: "mo",   role: "Also / too",          ex: "私も学生です",         exRo: "watashi mo gakusei desu",  exNe: "म पनि विद्यार्थी हुँ", note: "Replaces は/が/を to mean 'also'." },
          { p: "から", ro: "kara", role: "From / because",    ex: "9時から働きます",      exRo: "ku-ji kara hatarakimasu",  exNe: "९ बजेदेखि काम गर्छु",  note: "Start point / clause-end 'because'." },
          { p: "まで", ro: "made", role: "Until / up to",     ex: "5時まで",              exRo: "go-ji made",               exNe: "५ बजेसम्म",         note: "End point of time or place." },
          { p: "より", ro: "yori", role: "Than (comparison)", ex: "犬より猫が好き",       exRo: "inu yori neko ga suki",    exNe: "कुकुर भन्दा बिरालो मन पर्छ", note: "X より Y — yori comes after the LESSER." },
          { p: "か", ro: "ka",   role: "Question marker",     ex: "学生ですか",          exRo: "gakusei desu ka",          exNe: "विद्यार्थी हो?",     note: "Sentence-end = question. Also 'A か B' = 'or'." },
          { p: "よ", ro: "yo",   role: "Assertion / emphasis", ex: "おいしいですよ",       exRo: "oishii desu yo",           exNe: "मीठो छ नि",         note: "Tells listener something they don't know." },
          { p: "ね", ro: "ne",   role: "Confirmation",        ex: "暑いですね",          exRo: "atsui desu ne",            exNe: "गर्मी छ, होइन र?",   note: "Seeking agreement; like 'isn't it?'" },
        ],
      },
      {
        label: "2", title: "Workplace / IT",
        rows: [
          { p: "は", ro: "wa",   role: "Topic marker",        ex: "私はエンジニアです",    exRo: "watashi wa enjinia desu",      exNe: "म इन्जिनियर हुँ",     note: "Sets the topic — same in every context." },
          { p: "が", ro: "ga",   role: "Subject / new info",  ex: "バグがあります",        exRo: "bagu ga arimasu",              exNe: "बग छ",             note: "New info introduced — 'a bug exists'." },
          { p: "を", ro: "o",    role: "Direct object",       ex: "コードを書きます",      exRo: "kōdo o kakimasu",              exNe: "कोड लेख्छु",        note: "What the verb acts on — write CODE." },
          { p: "の", ro: "no",   role: "Possessive / linker", ex: "私の会社のコード",      exRo: "watashi no kaisha no kōdo",    exNe: "मेरो कम्पनीको कोड",  note: "Chain freely: my-company's-code." },
          { p: "に", ro: "ni",   role: "Target / time",       ex: "会議に行きます",        exRo: "kaigi ni ikimasu",             exNe: "बैठकमा जान्छु",     note: "Heading to a meeting." },
          { p: "で", ro: "de",   role: "Location of action",  ex: "会社で働きます",        exRo: "kaisha de hatarakimasu",       exNe: "अफिसमा काम गर्छु",  note: "Where the working happens." },
          { p: "へ", ro: "e",    role: "Direction",           ex: "東京オフィスへ行きます", exRo: "tōkyō ofisu e ikimasu",        exNe: "टोकियो अफिस तिर जान्छु", note: "Heading toward an office." },
          { p: "と", ro: "to",   role: "With / and",          ex: "同僚と話します",        exRo: "dōryō to hanashimasu",         exNe: "सहकर्मीसँग कुरा गर्छु", note: "With a colleague." },
          { p: "や", ro: "ya",   role: "And (open list)",     ex: "コードやテスト",        exRo: "kōdo ya tesuto",               exNe: "कोड, टेस्ट, आदि",   note: "Code, tests, and other things." },
          { p: "も", ro: "mo",   role: "Also / too",          ex: "私もチームのメンバーです", exRo: "watashi mo chīmu no menbā desu", exNe: "म पनि टिमको सदस्य हुँ", note: "I am ALSO a team member." },
          { p: "から", ro: "kara", role: "From / because",    ex: "9時から働きます",       exRo: "ku-ji kara hatarakimasu",       exNe: "९ बजेदेखि काम गर्छु",  note: "Work starts at 9." },
          { p: "まで", ro: "made", role: "Until / up to",     ex: "6時まで仕事です",       exRo: "roku-ji made shigoto desu",     exNe: "६ बजेसम्म काम छ",   note: "Work until 6." },
          { p: "より", ro: "yori", role: "Than (comparison)", ex: "昨日より忙しいです",    exRo: "kinō yori isogashii desu",     exNe: "हिजो भन्दा व्यस्त छु",  note: "Busier than yesterday." },
          { p: "か", ro: "ka",   role: "Question marker",     ex: "会議は何時ですか",      exRo: "kaigi wa nan-ji desu ka",      exNe: "बैठक कति बजे हो?",  note: "Asking for meeting time." },
          { p: "よ", ro: "yo",   role: "Assertion / emphasis", ex: "終わりましたよ",        exRo: "owarimashita yo",              exNe: "सकियो नि",        note: "Informing teammate 'it's done!'" },
          { p: "ね", ro: "ne",   role: "Confirmation",        ex: "大変ですね",            exRo: "taihen desu ne",               exNe: "गाह्रो छ, होइन र?",  note: "Seeking sympathy with colleague." },
        ],
      },
      {
        label: "3", title: "Restaurant / shopping",
        rows: [
          { p: "は", ro: "wa",   role: "Topic marker",        ex: "これはメニューです",    exRo: "kore wa menyū desu",          exNe: "यो मेनु हो",          note: "Pointing out the menu." },
          { p: "が", ro: "ga",   role: "Subject / new info",  ex: "テーブルがあります",    exRo: "tēburu ga arimasu",           exNe: "टेबल छ",             note: "Announcing 'there's a table'." },
          { p: "を", ro: "o",    role: "Direct object",       ex: "コーヒーを注文します",  exRo: "kōhī o chūmon shimasu",       exNe: "कफी अर्डर गर्छु",     note: "Ordering coffee." },
          { p: "の", ro: "no",   role: "Possessive / linker", ex: "この店のラーメン",      exRo: "kono mise no rāmen",          exNe: "यो पसलको रामेन",     note: "This shop's ramen." },
          { p: "に", ro: "ni",   role: "Target / time",       ex: "店に入ります",          exRo: "mise ni hairimasu",           exNe: "पसलमा छिर्छु",       note: "Entering the shop." },
          { p: "で", ro: "de",   role: "Location of action",  ex: "店で買います",          exRo: "mise de kaimasu",             exNe: "पसलमा किन्छु",       note: "Buying AT the shop." },
          { p: "へ", ro: "e",    role: "Direction",           ex: "コンビニへ行きます",    exRo: "konbini e ikimasu",           exNe: "कन्भिनी तिर जान्छु",  note: "Heading to convenience store." },
          { p: "と", ro: "to",   role: "With / and",          ex: "友達とランチ",          exRo: "tomodachi to ranchi",         exNe: "साथीसँग खाजा",       note: "Lunch with a friend." },
          { p: "や", ro: "ya",   role: "And (open list)",     ex: "寿司やラーメン",        exRo: "sushi ya rāmen",              exNe: "सुसी, रामेन, आदि",    note: "Sushi, ramen, and others." },
          { p: "も", ro: "mo",   role: "Also / too",          ex: "お茶もください",        exRo: "ocha mo kudasai",             exNe: "चिया पनि दिनुहोस्",   note: "Also tea, please." },
          { p: "から", ro: "kara", role: "From / because",    ex: "千円からあります",      exRo: "sen-en kara arimasu",         exNe: "१००० येनदेखि छ",     note: "Available from 1000 yen." },
          { p: "まで", ro: "made", role: "Until / up to",     ex: "22時まで開いています",  exRo: "ni-jū-ni-ji made aite imasu", exNe: "१० बजे राति सम्म खुला छ", note: "Open until 10 PM." },
          { p: "より", ro: "yori", role: "Than (comparison)", ex: "昨日より安いです",      exRo: "kinō yori yasui desu",        exNe: "हिजो भन्दा सस्तो छ",  note: "Cheaper than yesterday." },
          { p: "か", ro: "ka",   role: "Question marker",     ex: "いくらですか",          exRo: "ikura desu ka",               exNe: "कति हो?",            note: "Asking the price." },
          { p: "よ", ro: "yo",   role: "Assertion / emphasis", ex: "とてもおいしいですよ", exRo: "totemo oishii desu yo",       exNe: "धेरै मीठो छ नि",      note: "Recommending: 'it's tasty!'" },
          { p: "ね", ro: "ne",   role: "Confirmation",        ex: "高いですね",            exRo: "takai desu ne",               exNe: "महँगो छ, होइन र?",   note: "Reacting to price." },
        ],
      },
      {
        label: "4", title: "Travel / directions",
        rows: [
          { p: "は", ro: "wa",   role: "Topic marker",        ex: "駅はどこですか",        exRo: "eki wa doko desu ka",         exNe: "स्टेशन कहाँ छ?",      note: "Topic = the station; asking location." },
          { p: "が", ro: "ga",   role: "Subject / new info",  ex: "ホテルがあります",      exRo: "hoteru ga arimasu",           exNe: "होटेल छ",            note: "There's a hotel (introducing)." },
          { p: "を", ro: "o",    role: "Direct object",       ex: "切符を買います",        exRo: "kippu o kaimasu",             exNe: "टिकट किन्छु",        note: "Buying a ticket." },
          { p: "の", ro: "no",   role: "Possessive / linker", ex: "京都の地図",            exRo: "kyōto no chizu",              exNe: "क्योटोको नक्सा",      note: "Kyoto's map." },
          { p: "に", ro: "ni",   role: "Target / time",       ex: "駅に着きます",          exRo: "eki ni tsukimasu",            exNe: "स्टेशन पुग्छु",       note: "Arriving at the station." },
          { p: "で", ro: "de",   role: "Location of action",  ex: "新幹線で行きます",      exRo: "shinkansen de ikimasu",       exNe: "बुलेट ट्रेनबाट जान्छु", note: "BY means — by bullet train." },
          { p: "へ", ro: "e",    role: "Direction",           ex: "京都へ行きます",        exRo: "kyōto e ikimasu",             exNe: "क्योटो तिर जान्छु",   note: "Heading to Kyoto." },
          { p: "と", ro: "to",   role: "With / and",          ex: "家族と旅行します",      exRo: "kazoku to ryokō shimasu",     exNe: "परिवारसँग यात्रा गर्छु", note: "Travel with family." },
          { p: "や", ro: "ya",   role: "And (open list)",     ex: "京都や奈良",            exRo: "kyōto ya nara",               exNe: "क्योटो, नारा, आदि",   note: "Kyoto, Nara, and others." },
          { p: "も", ro: "mo",   role: "Also / too",          ex: "富士山も見たいです",    exRo: "fujisan mo mitai desu",       exNe: "फूजी पनि हेर्न मन छ",  note: "Want to see Mt. Fuji TOO." },
          { p: "から", ro: "kara", role: "From / because",    ex: "東京から京都まで",      exRo: "tōkyō kara kyōto made",       exNe: "टोकियोदेखि क्योटोसम्म", note: "From Tokyo to Kyoto." },
          { p: "まで", ro: "made", role: "Until / up to",     ex: "京都まで2時間です",     exRo: "kyōto made ni-jikan desu",    exNe: "क्योटो सम्म २ घण्टा",  note: "Up to Kyoto takes 2 hours." },
          { p: "より", ro: "yori", role: "Than (comparison)", ex: "新幹線より飛行機が早い", exRo: "shinkansen yori hikōki ga hayai", exNe: "बुलेट ट्रेन भन्दा हवाई जहाज छिटो", note: "Plane is faster than bullet train." },
          { p: "か", ro: "ka",   role: "Question marker",     ex: "ホテルですか",          exRo: "hoteru desu ka",              exNe: "होटेल हो?",           note: "Is this the hotel?" },
          { p: "よ", ro: "yo",   role: "Assertion / emphasis", ex: "着きましたよ",          exRo: "tsukimashita yo",             exNe: "पुग्यौँ नि",          note: "'We've arrived!'" },
          { p: "ね", ro: "ne",   role: "Confirmation",        ex: "美しいですね",          exRo: "utsukushii desu ne",          exNe: "सुन्दर छ, होइन र?",   note: "Reacting to scenery." },
        ],
      },
      {
        label: "5", title: "School / study",
        rows: [
          { p: "は", ro: "wa",   role: "Topic marker",        ex: "これは教科書です",      exRo: "kore wa kyōkasho desu",       exNe: "यो पाठ्यपुस्तक हो",   note: "Topic = this; identifying a textbook." },
          { p: "が", ro: "ga",   role: "Subject / new info",  ex: "宿題があります",        exRo: "shukudai ga arimasu",         exNe: "गृहकार्य छ",         note: "Announcing 'there's homework'." },
          { p: "を", ro: "o",    role: "Direct object",       ex: "日本語を勉強します",    exRo: "nihongo o benkyō shimasu",    exNe: "जापानी पढ्छु",       note: "Studying Japanese (the object)." },
          { p: "の", ro: "no",   role: "Possessive / linker", ex: "学校の図書館",          exRo: "gakkō no toshokan",           exNe: "स्कूलको पुस्तकालय",  note: "School's library." },
          { p: "に", ro: "ni",   role: "Target / time",       ex: "学校に行きます",        exRo: "gakkō ni ikimasu",            exNe: "स्कूल जान्छु",       note: "Heading to school." },
          { p: "で", ro: "de",   role: "Location of action",  ex: "図書館で勉強します",    exRo: "toshokan de benkyō shimasu",  exNe: "पुस्तकालयमा पढ्छु",   note: "Studying AT the library." },
          { p: "へ", ro: "e",    role: "Direction",           ex: "教室へ行きます",        exRo: "kyōshitsu e ikimasu",         exNe: "कक्षाकोठा तिर जान्छु", note: "Heading to classroom." },
          { p: "と", ro: "to",   role: "With / and",          ex: "友達と勉強します",      exRo: "tomodachi to benkyō shimasu", exNe: "साथीसँग पढ्छु",      note: "Study with a friend." },
          { p: "や", ro: "ya",   role: "And (open list)",     ex: "漢字や文法",            exRo: "kanji ya bunpō",              exNe: "कान्जी, व्याकरण, आदि",note: "Kanji, grammar, and others." },
          { p: "も", ro: "mo",   role: "Also / too",          ex: "私も勉強します",        exRo: "watashi mo benkyō shimasu",   exNe: "म पनि पढ्छु",         note: "I ALSO study." },
          { p: "から", ro: "kara", role: "From / because",    ex: "月曜日から授業です",    exRo: "getsuyōbi kara jugyō desu",   exNe: "सोमबारदेखि कक्षा छ",  note: "Class starts from Monday." },
          { p: "まで", ro: "made", role: "Until / up to",     ex: "試験まで一週間です",    exRo: "shiken made isshūkan desu",   exNe: "परीक्षा सम्म १ हप्ता", note: "One week until the exam." },
          { p: "より", ro: "yori", role: "Than (comparison)", ex: "数学より日本語が好き",  exRo: "sūgaku yori nihongo ga suki", exNe: "गणित भन्दा जापानी मन पर्छ", note: "Prefer Japanese to math." },
          { p: "か", ro: "ka",   role: "Question marker",     ex: "学生ですか",            exRo: "gakusei desu ka",             exNe: "विद्यार्थी हो?",      note: "Are you a student?" },
          { p: "よ", ro: "yo",   role: "Assertion / emphasis", ex: "難しいですよ",          exRo: "muzukashii desu yo",          exNe: "गाह्रो छ नि",         note: "Warning: 'it's difficult!'" },
          { p: "ね", ro: "ne",   role: "Confirmation",        ex: "楽しいですね",          exRo: "tanoshii desu ne",            exNe: "रमाइलो छ, होइन र?",   note: "'Class is fun, isn't it?'" },
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // PERSONS — same 7 entries, 5 example contexts
  // ════════════════════════════════════════════════════════════════
  persons: {
    intro: "Japanese drops pronouns a lot. These are the forms you'll need when context isn't clear. Same 7 entries, 5 example contexts.",
    sets: [
      {
        label: "1", title: "Daily life",
        rows: [
          { person: "1st singular (I)",  casual: "僕 / 俺",  casualRo: "boku / ore",  polite: "私",          politeRo: "watashi",         plural: "私たち",      pluralRo: "watashi-tachi", ex: "私はシシルです",        exRo: "watashi wa Shishir desu",     exNe: "म शिशिर हुँ",         note: "僕 casual male, 俺 rough male, 私 neutral." },
          { person: "We (inclusive)",   casual: "僕たち",   casualRo: "boku-tachi",  polite: "私たち",     politeRo: "watashi-tachi",   plural: "—",          pluralRo: "",              ex: "私たちは学生です",      exRo: "watashi-tachi wa gakusei desu", exNe: "हामी विद्यार्थी हौं",  note: "Same word = 'we' and 'us'." },
          { person: "2nd singular (you)", casual: "君 / お前", casualRo: "kimi / omae", polite: "あなた",     politeRo: "anata",           plural: "あなたたち", pluralRo: "anata-tachi",   ex: "あなたは誰ですか",      exRo: "anata wa dare desu ka",       exNe: "तपाईं को हो?",        note: "Often AVOIDED. Use NAME + さん." },
          { person: "3rd singular (he)", casual: "彼",       casualRo: "kare",        polite: "彼",         politeRo: "kare",            plural: "彼ら",       pluralRo: "karera",        ex: "彼は友達です",          exRo: "kare wa tomodachi desu",      exNe: "ऊ साथी हो",          note: "Also means 'boyfriend'. Prefer name + さん." },
          { person: "3rd singular (she)", casual: "彼女",    casualRo: "kanojo",      polite: "彼女",       politeRo: "kanojo",          plural: "彼女たち",   pluralRo: "kanojo-tachi",  ex: "彼女は学生です",        exRo: "kanojo wa gakusei desu",      exNe: "उनी विद्यार्थी हुन्",  note: "Also means 'girlfriend'." },
          { person: "3rd (this person)", casual: "この人",   casualRo: "kono hito",   polite: "こちらの方", politeRo: "kochira no kata", plural: "この人たち", pluralRo: "kono hito-tachi", ex: "この人は田中さんです",  exRo: "kono hito wa Tanaka-san desu", exNe: "यो व्यक्ति तानाका हो", note: "Polite = こちら ('this side')." },
          { person: "Honorific suffix", casual: "—",         casualRo: "",            polite: "〜さん / 〜様", politeRo: "-san / -sama", plural: "—",          pluralRo: "",              ex: "田中さん、こんにちは",  exRo: "Tanaka-san, konnichiwa",      exNe: "तानाका जी, नमस्ते",   note: "Attach to NAME. Never use for yourself." },
        ],
      },
      {
        label: "2", title: "Workplace / IT",
        rows: [
          { person: "1st singular (I)",  casual: "僕 / 俺",  casualRo: "boku / ore",  polite: "私",          politeRo: "watashi",         plural: "私たち",      pluralRo: "watashi-tachi", ex: "私はエンジニアです",    exRo: "watashi wa enjinia desu",     exNe: "म इन्जिनियर हुँ",      note: "Use 私 at work — always safe." },
          { person: "We (inclusive)",   casual: "僕たち",   casualRo: "boku-tachi",  polite: "私たち",     politeRo: "watashi-tachi",   plural: "—",          pluralRo: "",              ex: "私たちのチームです",    exRo: "watashi-tachi no chīmu desu", exNe: "हाम्रो टिम हो",       note: "Our team — common in standups." },
          { person: "2nd singular (you)", casual: "君 / お前", casualRo: "kimi / omae", polite: "あなた",     politeRo: "anata",           plural: "あなたたち", pluralRo: "anata-tachi",   ex: "田中さんはレビューしますか", exRo: "Tanaka-san wa rebyū shimasu ka", exNe: "तानाका जीले रिभ्यू गर्नुहुन्छ?", note: "At work use NAME + さん, not あなた." },
          { person: "3rd singular (he)", casual: "彼",       casualRo: "kare",        polite: "彼",         politeRo: "kare",            plural: "彼ら",       pluralRo: "karera",        ex: "彼はリードエンジニアです", exRo: "kare wa rīdo enjinia desu",   exNe: "ऊ लीड इन्जिनियर हो",  note: "Describing a colleague (3rd person)." },
          { person: "3rd singular (she)", casual: "彼女",    casualRo: "kanojo",      polite: "彼女",       politeRo: "kanojo",          plural: "彼女たち",   pluralRo: "kanojo-tachi",  ex: "彼女はPMです",          exRo: "kanojo wa PM desu",           exNe: "उनी पीएम हुन्",       note: "Prefer 鈴木さん over 彼女 in formal speech." },
          { person: "3rd (this person)", casual: "この人",   casualRo: "kono hito",   polite: "こちらの方", politeRo: "kochira no kata", plural: "この人たち", pluralRo: "kono hito-tachi", ex: "こちらは新しい同僚です", exRo: "kochira wa atarashii dōryō desu", exNe: "यिनी नयाँ सहकर्मी हुनुहुन्छ", note: "Introducing a new colleague politely." },
          { person: "Honorific suffix", casual: "—",         casualRo: "",            polite: "〜さん / 〜様", politeRo: "-san / -sama", plural: "—",          pluralRo: "",              ex: "鈴木様、お疲れさまです", exRo: "Suzuki-sama, otsukaresama desu", exNe: "सुजुकी सर, थाक्नुभयो होला", note: "様 for clients/customers; さん internally." },
        ],
      },
      {
        label: "3", title: "Restaurant / shopping",
        rows: [
          { person: "1st singular (I)",  casual: "僕 / 俺",  casualRo: "boku / ore",  polite: "私",          politeRo: "watashi",         plural: "私たち",      pluralRo: "watashi-tachi", ex: "私はコーヒーをください",   exRo: "watashi wa kōhī o kudasai",   exNe: "मलाई कफी दिनुहोस्",    note: "Ordering — context makes 'I' clear, usually drop it." },
          { person: "We (inclusive)",   casual: "僕たち",   casualRo: "boku-tachi",  polite: "私たち",     politeRo: "watashi-tachi",   plural: "—",          pluralRo: "",              ex: "私たちは2人です",       exRo: "watashi-tachi wa futari desu", exNe: "हामी दुई जना हौं",     note: "Telling waiter group size." },
          { person: "2nd singular (you)", casual: "君 / お前", casualRo: "kimi / omae", polite: "あなた",     politeRo: "anata",           plural: "あなたたち", pluralRo: "anata-tachi",   ex: "お客様、何になさいますか", exRo: "okyaku-sama, nan ni nasaimasu ka", exNe: "ग्राहक जी, के लिनुहुन्छ?", note: "Staff to customer = お客様 (very polite)." },
          { person: "3rd singular (he)", casual: "彼",       casualRo: "kare",        polite: "彼",         politeRo: "kare",            plural: "彼ら",       pluralRo: "karera",        ex: "彼はお茶を飲みます",    exRo: "kare wa ocha o nomimasu",     exNe: "ऊ चिया पिउँछ",        note: "Ordering on someone else's behalf." },
          { person: "3rd singular (she)", casual: "彼女",    casualRo: "kanojo",      polite: "彼女",       politeRo: "kanojo",          plural: "彼女たち",   pluralRo: "kanojo-tachi",  ex: "彼女は寿司が好きです",  exRo: "kanojo wa sushi ga suki desu", exNe: "उनलाई सुसी मन पर्छ",   note: "Mentioning her preference at a restaurant." },
          { person: "3rd (this person)", casual: "この人",   casualRo: "kono hito",   polite: "こちらの方", politeRo: "kochira no kata", plural: "この人たち", pluralRo: "kono hito-tachi", ex: "こちらの方はビーガンです", exRo: "kochira no kata wa bīgan desu", exNe: "यिनी भिगन हुनुहुन्छ",   note: "Telling staff about a dining partner." },
          { person: "Honorific suffix", casual: "—",         casualRo: "",            polite: "〜さん / 〜様", politeRo: "-san / -sama", plural: "—",          pluralRo: "",              ex: "お客様、ありがとうございます", exRo: "okyaku-sama, arigatō gozaimasu", exNe: "ग्राहक जी, धन्यवाद",   note: "Staff thanking customer." },
        ],
      },
      {
        label: "4", title: "Travel / directions",
        rows: [
          { person: "1st singular (I)",  casual: "僕 / 俺",  casualRo: "boku / ore",  polite: "私",          politeRo: "watashi",         plural: "私たち",      pluralRo: "watashi-tachi", ex: "私は道に迷いました",    exRo: "watashi wa michi ni mayoimashita", exNe: "म बाटो हराएँ",       note: "Asking for help when lost." },
          { person: "We (inclusive)",   casual: "僕たち",   casualRo: "boku-tachi",  polite: "私たち",     politeRo: "watashi-tachi",   plural: "—",          pluralRo: "",              ex: "私たちは観光客です",    exRo: "watashi-tachi wa kankōkyaku desu", exNe: "हामी पर्यटक हौं",    note: "Identifying as tourists." },
          { person: "2nd singular (you)", casual: "君 / お前", casualRo: "kimi / omae", polite: "あなた",     politeRo: "anata",           plural: "あなたたち", pluralRo: "anata-tachi",   ex: "あなたはどこから来ましたか", exRo: "anata wa doko kara kimashita ka", exNe: "तपाईं कहाँबाट आउनुभयो?", note: "Hostel chat — OK because stranger." },
          { person: "3rd singular (he)", casual: "彼",       casualRo: "kare",        polite: "彼",         politeRo: "kare",            plural: "彼ら",       pluralRo: "karera",        ex: "彼はガイドです",        exRo: "kare wa gaido desu",          exNe: "ऊ गाइड हो",          note: "Introducing your tour guide." },
          { person: "3rd singular (she)", casual: "彼女",    casualRo: "kanojo",      polite: "彼女",       politeRo: "kanojo",          plural: "彼女たち",   pluralRo: "kanojo-tachi",  ex: "彼女は日本人ですか",    exRo: "kanojo wa nihonjin desu ka",  exNe: "उनी जापानी हो?",      note: "Asking about someone in your group." },
          { person: "3rd (this person)", casual: "この人",   casualRo: "kono hito",   polite: "こちらの方", politeRo: "kochira no kata", plural: "この人たち", pluralRo: "kono hito-tachi", ex: "この人は道を知っています", exRo: "kono hito wa michi o shitte imasu", exNe: "यो व्यक्तिले बाटो जान्दछ", note: "Pointing out a local who knows the way." },
          { person: "Honorific suffix", casual: "—",         casualRo: "",            polite: "〜さん / 〜様", politeRo: "-san / -sama", plural: "—",          pluralRo: "",              ex: "すみません、駅員さん",  exRo: "sumimasen, ekiin-san",        exNe: "माफ गर्नुस्, स्टेशन कर्मचारी जी", note: "〜さん to address station staff." },
        ],
      },
      {
        label: "5", title: "School / study",
        rows: [
          { person: "1st singular (I)",  casual: "僕 / 俺",  casualRo: "boku / ore",  polite: "私",          politeRo: "watashi",         plural: "私たち",      pluralRo: "watashi-tachi", ex: "私は日本語を勉強しています", exRo: "watashi wa nihongo o benkyō shite imasu", exNe: "म जापानी पढ्दैछु",    note: "Introducing yourself as a student." },
          { person: "We (inclusive)",   casual: "僕たち",   casualRo: "boku-tachi",  polite: "私たち",     politeRo: "watashi-tachi",   plural: "—",          pluralRo: "",              ex: "私たちのクラス",        exRo: "watashi-tachi no kurasu",     exNe: "हाम्रो कक्षा",        note: "Our class — common in school." },
          { person: "2nd singular (you)", casual: "君 / お前", casualRo: "kimi / omae", polite: "あなた",     politeRo: "anata",           plural: "あなたたち", pluralRo: "anata-tachi",   ex: "君の宿題は終わった？", exRo: "kimi no shukudai wa owatta?", exNe: "तिम्रो गृहकार्य सकियो?",note: "君 OK between students of similar age." },
          { person: "3rd singular (he)", casual: "彼",       casualRo: "kare",        polite: "彼",         politeRo: "kare",            plural: "彼ら",       pluralRo: "karera",        ex: "彼はクラスメートです",  exRo: "kare wa kurasumēto desu",     exNe: "ऊ सहपाठी हो",        note: "Describing a classmate." },
          { person: "3rd singular (she)", casual: "彼女",    casualRo: "kanojo",      polite: "彼女",       politeRo: "kanojo",          plural: "彼女たち",   pluralRo: "kanojo-tachi",  ex: "彼女は先生です",        exRo: "kanojo wa sensei desu",       exNe: "उनी शिक्षिका हुन्",   note: "Talking about a teacher (3rd person)." },
          { person: "3rd (this person)", casual: "この人",   casualRo: "kono hito",   polite: "こちらの方", politeRo: "kochira no kata", plural: "この人たち", pluralRo: "kono hito-tachi", ex: "こちらは田中先生です",  exRo: "kochira wa Tanaka-sensei desu", exNe: "यहाँ तानाका शिक्षक हुनुहुन्छ", note: "Introducing a teacher politely." },
          { person: "Honorific suffix", casual: "—",         casualRo: "",            polite: "〜さん / 〜先生", politeRo: "-san / -sensei", plural: "—",       pluralRo: "",              ex: "山田先生、質問があります", exRo: "Yamada-sensei, shitsumon ga arimasu", exNe: "यामादा सर, प्रश्न छ", note: "先生 (sensei) for teachers — replaces さん." },
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // QUESTION WORDS — same 12 words, 5 example contexts
  // ════════════════════════════════════════════════════════════════
  questions: {
    intro: "Same 12 question words you'll need every day. Five contexts — see how each one looks in real situations.",
    sets: [
      {
        label: "1", title: "Daily life",
        rows: [
          { q: "何 / なに",    ro: "nani / nan",      meaning: "what",        ex: "これは何ですか",          exRo: "kore wa nan desu ka",         exNe: "यो के हो?",         note: "Read 'nan' before counters/copula, 'nani' alone." },
          { q: "誰",          ro: "dare",            meaning: "who",         ex: "あの人は誰ですか",        exRo: "ano hito wa dare desu ka",    exNe: "ऊ को हो?",          note: "More polite: どなた (donata)." },
          { q: "どこ",        ro: "doko",            meaning: "where",       ex: "トイレはどこですか",      exRo: "toire wa doko desu ka",       exNe: "शौचालय कहाँ छ?",     note: "どちら is more polite for direction." },
          { q: "いつ",        ro: "itsu",            meaning: "when",        ex: "誕生日はいつですか",      exRo: "tanjōbi wa itsu desu ka",     exNe: "जन्मदिन कहिले हो?",  note: "No particle after いつ in most uses." },
          { q: "どう",        ro: "dō",              meaning: "how",         ex: "味はどうですか",          exRo: "aji wa dō desu ka",           exNe: "स्वाद कस्तो छ?",     note: "Also asks for opinion." },
          { q: "なぜ / どうして", ro: "naze / dōshite", meaning: "why",         ex: "どうして遅れましたか",   exRo: "dōshite okuremashita ka",      exNe: "किन ढिलो भयो?",     note: "なぜ formal/written; どうして everyday." },
          { q: "どれ",        ro: "dore",            meaning: "which (of 3+)", ex: "どれが好きですか",     exRo: "dore ga suki desu ka",        exNe: "कुन मन पर्छ?",       note: "Stand-alone. どの+noun = 'which X'." },
          { q: "どの",        ro: "dono",            meaning: "which (+noun)", ex: "どの本ですか",          exRo: "dono hon desu ka",            exNe: "कुन किताब हो?",      note: "Always followed by a noun." },
          { q: "いくら",      ro: "ikura",           meaning: "how much (cost)", ex: "これはいくらですか",  exRo: "kore wa ikura desu ka",       exNe: "यो कति हो?",         note: "Specifically for price/amount." },
          { q: "いくつ",      ro: "ikutsu",          meaning: "how many",     ex: "いくつありますか",        exRo: "ikutsu arimasu ka",           exNe: "कति वटा छ?",         note: "General counter. Also asks age (polite for kids)." },
          { q: "どのくらい",  ro: "dono kurai",      meaning: "how long/much", ex: "どのくらいかかりますか", exRo: "dono kurai kakarimasu ka",    exNe: "कति समय लाग्छ?",     note: "Duration, distance, quantity." },
          { q: "何時",        ro: "nan-ji",          meaning: "what time",   ex: "今、何時ですか",          exRo: "ima, nan-ji desu ka",         exNe: "अहिले कति बजे हो?",  note: "何 + counter: 何人, 何枚, 何回 etc." },
        ],
      },
      {
        label: "2", title: "Workplace / IT",
        rows: [
          { q: "何 / なに",    ro: "nani / nan",      meaning: "what",        ex: "今日の議題は何ですか",     exRo: "kyō no gidai wa nan desu ka", exNe: "आजको एजेन्डा के हो?",  note: "Asking what's on the meeting agenda." },
          { q: "誰",          ro: "dare",            meaning: "who",         ex: "このコードを書いたのは誰ですか", exRo: "kono kōdo o kaita no wa dare desu ka", exNe: "यो कोड कसले लेखेको हो?", note: "Asking who wrote the code." },
          { q: "どこ",        ro: "doko",            meaning: "where",       ex: "会議室はどこですか",      exRo: "kaigishitsu wa doko desu ka", exNe: "बैठक कोठा कहाँ छ?",    note: "Finding the meeting room." },
          { q: "いつ",        ro: "itsu",            meaning: "when",        ex: "リリースはいつですか",    exRo: "rirīsu wa itsu desu ka",      exNe: "रिलिज कहिले हो?",      note: "When is the release scheduled." },
          { q: "どう",        ro: "dō",              meaning: "how",         ex: "プロジェクトはどうですか", exRo: "purojekuto wa dō desu ka",    exNe: "प्रोजेक्ट कस्तो छ?",    note: "How's the project going?" },
          { q: "なぜ / どうして", ro: "naze / dōshite", meaning: "why",         ex: "どうしてバグが出ましたか", exRo: "dōshite bagu ga demashita ka", exNe: "किन बग आयो?",         note: "Asking why a bug appeared." },
          { q: "どれ",        ro: "dore",            meaning: "which (of 3+)", ex: "どれが本番ですか",      exRo: "dore ga honban desu ka",      exNe: "कुन प्रोडक्शन हो?",    note: "Which environment is production?" },
          { q: "どの",        ro: "dono",            meaning: "which (+noun)", ex: "どのブランチですか",    exRo: "dono buranchi desu ka",       exNe: "कुन ब्रान्च हो?",      note: "Which branch (git)." },
          { q: "いくら",      ro: "ikura",           meaning: "how much (cost)", ex: "サーバー代はいくらですか", exRo: "sābā-dai wa ikura desu ka", exNe: "सर्भर शुल्क कति हो?",   note: "Server cost." },
          { q: "いくつ",      ro: "ikutsu",          meaning: "how many",     ex: "タスクはいくつありますか", exRo: "tasuku wa ikutsu arimasu ka", exNe: "कति वटा टास्क छ?",     note: "How many tasks open." },
          { q: "どのくらい",  ro: "dono kurai",      meaning: "how long/much", ex: "どのくらいかかりますか", exRo: "dono kurai kakarimasu ka",    exNe: "कति समय लाग्छ?",      note: "How long will it take." },
          { q: "何時",        ro: "nan-ji",          meaning: "what time",   ex: "ミーティングは何時からですか", exRo: "mītingu wa nan-ji kara desu ka", exNe: "मीटिङ कति बजेदेखि?",  note: "What time does the meeting start." },
        ],
      },
      {
        label: "3", title: "Restaurant / shopping",
        rows: [
          { q: "何 / なに",    ro: "nani / nan",      meaning: "what",        ex: "おすすめは何ですか",      exRo: "osusume wa nan desu ka",      exNe: "सिफारिस के हो?",       note: "Asking for recommendation." },
          { q: "誰",          ro: "dare",            meaning: "who",         ex: "誰のですか",              exRo: "dare no desu ka",             exNe: "कसको हो?",            note: "Whose order is this?" },
          { q: "どこ",        ro: "doko",            meaning: "where",       ex: "レジはどこですか",        exRo: "reji wa doko desu ka",        exNe: "क्यासियर कहाँ छ?",      note: "Where's the cashier?" },
          { q: "いつ",        ro: "itsu",            meaning: "when",        ex: "閉店はいつですか",        exRo: "heiten wa itsu desu ka",      exNe: "बन्द हुने समय कहिले?",  note: "When does it close?" },
          { q: "どう",        ro: "dō",              meaning: "how",         ex: "サイズはどうですか",      exRo: "saizu wa dō desu ka",         exNe: "साइज कस्तो छ?",        note: "Trying on clothing." },
          { q: "なぜ / どうして", ro: "naze / dōshite", meaning: "why",         ex: "どうして売り切れですか", exRo: "dōshite urikire desu ka",     exNe: "किन सकियो?",          note: "Why is it sold out?" },
          { q: "どれ",        ro: "dore",            meaning: "which (of 3+)", ex: "どれがおいしいですか",  exRo: "dore ga oishii desu ka",      exNe: "कुन मिठो छ?",          note: "Asking which is tasty." },
          { q: "どの",        ro: "dono",            meaning: "which (+noun)", ex: "どの色がありますか",    exRo: "dono iro ga arimasu ka",      exNe: "कुन रङ छ?",           note: "Which color is available?" },
          { q: "いくら",      ro: "ikura",           meaning: "how much (cost)", ex: "これはいくらですか",  exRo: "kore wa ikura desu ka",       exNe: "यो कति हो?",          note: "Most common — asking the price." },
          { q: "いくつ",      ro: "ikutsu",          meaning: "how many",     ex: "いくつご注文ですか",      exRo: "ikutsu go-chūmon desu ka",    exNe: "कति वटा अर्डर?",       note: "Staff asking how many you'd like." },
          { q: "どのくらい",  ro: "dono kurai",      meaning: "how long/much", ex: "賞味期限はどのくらいですか", exRo: "shōmikigen wa dono kurai desu ka", exNe: "उपयोगिता अवधि कति लामो?", note: "How long is the shelf life?" },
          { q: "何時",        ro: "nan-ji",          meaning: "what time",   ex: "何時に開きますか",        exRo: "nan-ji ni akimasu ka",        exNe: "कति बजे खुल्छ?",       note: "What time does it open?" },
        ],
      },
      {
        label: "4", title: "Travel / directions",
        rows: [
          { q: "何 / なに",    ro: "nani / nan",      meaning: "what",        ex: "これは何駅ですか",        exRo: "kore wa nan-eki desu ka",     exNe: "यो कुन स्टेशन हो?",     note: "What station is this?" },
          { q: "誰",          ro: "dare",            meaning: "who",         ex: "ガイドは誰ですか",        exRo: "gaido wa dare desu ka",       exNe: "गाइड को हो?",          note: "Who's our guide?" },
          { q: "どこ",        ro: "doko",            meaning: "where",       ex: "ホテルはどこですか",      exRo: "hoteru wa doko desu ka",      exNe: "होटेल कहाँ छ?",        note: "Most common travel question." },
          { q: "いつ",        ro: "itsu",            meaning: "when",        ex: "電車はいつ来ますか",      exRo: "densha wa itsu kimasu ka",    exNe: "रेल कहिले आउँछ?",       note: "When does the train come?" },
          { q: "どう",        ro: "dō",              meaning: "how",         ex: "京都はどうでしたか",      exRo: "kyōto wa dō deshita ka",      exNe: "क्योटो कस्तो थियो?",    note: "How was Kyoto?" },
          { q: "なぜ / どうして", ro: "naze / dōshite", meaning: "why",         ex: "どうして遅れていますか", exRo: "dōshite okurete imasu ka",    exNe: "किन ढिलो भइरहेको छ?",  note: "Why is it delayed?" },
          { q: "どれ",        ro: "dore",            meaning: "which (of 3+)", ex: "どれが新幹線ですか",    exRo: "dore ga shinkansen desu ka",  exNe: "कुन बुलेट ट्रेन हो?",   note: "Which one is the bullet train?" },
          { q: "どの",        ro: "dono",            meaning: "which (+noun)", ex: "どのバスですか",        exRo: "dono basu desu ka",           exNe: "कुन बस हो?",           note: "Which bus to take?" },
          { q: "いくら",      ro: "ikura",           meaning: "how much (cost)", ex: "京都までいくらですか", exRo: "kyōto made ikura desu ka",    exNe: "क्योटोसम्म कति?",       note: "How much to Kyoto?" },
          { q: "いくつ",      ro: "ikutsu",          meaning: "how many",     ex: "切符をいくつ買いますか", exRo: "kippu o ikutsu kaimasu ka",   exNe: "कति वटा टिकट किन्ने?",  note: "How many tickets to buy." },
          { q: "どのくらい",  ro: "dono kurai",      meaning: "how long/much", ex: "京都までどのくらいですか", exRo: "kyōto made dono kurai desu ka", exNe: "क्योटोसम्म कति टाढा?", note: "How far/long to Kyoto?" },
          { q: "何時",        ro: "nan-ji",          meaning: "what time",   ex: "電車は何時に出ますか",   exRo: "densha wa nan-ji ni demasu ka", exNe: "रेल कति बजे जान्छ?",   note: "Departure time." },
        ],
      },
      {
        label: "5", title: "School / study",
        rows: [
          { q: "何 / なに",    ro: "nani / nan",      meaning: "what",        ex: "宿題は何ですか",          exRo: "shukudai wa nan desu ka",     exNe: "गृहकार्य के हो?",       note: "What's the homework?" },
          { q: "誰",          ro: "dare",            meaning: "who",         ex: "今日の先生は誰ですか",    exRo: "kyō no sensei wa dare desu ka", exNe: "आजको शिक्षक को हो?",  note: "Who's today's teacher?" },
          { q: "どこ",        ro: "doko",            meaning: "where",       ex: "図書館はどこですか",      exRo: "toshokan wa doko desu ka",    exNe: "पुस्तकालय कहाँ छ?",     note: "Where's the library?" },
          { q: "いつ",        ro: "itsu",            meaning: "when",        ex: "試験はいつですか",        exRo: "shiken wa itsu desu ka",      exNe: "परीक्षा कहिले हो?",    note: "When is the exam?" },
          { q: "どう",        ro: "dō",              meaning: "how",         ex: "授業はどうでしたか",      exRo: "jugyō wa dō deshita ka",      exNe: "कक्षा कस्तो थियो?",    note: "How was the class?" },
          { q: "なぜ / どうして", ro: "naze / dōshite", meaning: "why",         ex: "どうして来なかったの",   exRo: "dōshite konakatta no",        exNe: "किन आइनौ?",           note: "Why didn't you come?" },
          { q: "どれ",        ro: "dore",            meaning: "which (of 3+)", ex: "どれが正解ですか",      exRo: "dore ga seikai desu ka",      exNe: "कुन सही उत्तर हो?",    note: "Which is the correct answer?" },
          { q: "どの",        ro: "dono",            meaning: "which (+noun)", ex: "どの教科書ですか",      exRo: "dono kyōkasho desu ka",       exNe: "कुन पाठ्यपुस्तक?",      note: "Which textbook?" },
          { q: "いくら",      ro: "ikura",           meaning: "how much (cost)", ex: "教科書はいくらですか", exRo: "kyōkasho wa ikura desu ka",   exNe: "पाठ्यपुस्तक कति हो?",  note: "How much is the textbook?" },
          { q: "いくつ",      ro: "ikutsu",          meaning: "how many",     ex: "問題はいくつありますか",   exRo: "mondai wa ikutsu arimasu ka", exNe: "कति वटा प्रश्न छ?",    note: "How many questions are there?" },
          { q: "どのくらい",  ro: "dono kurai",      meaning: "how long/much", ex: "毎日どのくらい勉強しますか", exRo: "mainichi dono kurai benkyō shimasu ka", exNe: "दैनिक कति समय पढ्ने?", note: "How long do you study each day?" },
          { q: "何時",        ro: "nan-ji",          meaning: "what time",   ex: "授業は何時からですか",    exRo: "jugyō wa nan-ji kara desu ka", exNe: "कक्षा कति बजेदेखि?",    note: "When does class start?" },
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // CONFUSING PAIRS — same 10 pairs, 5 example contexts
  // ════════════════════════════════════════════════════════════════
  pairs: {
    intro: "Same 10 confusion-prone pairs you must memorize. Five different contexts so you see each pair in real situations.",
    sets: [
      {
        label: "1", title: "Daily life",
        rows: [
          { pair: "は vs が",          a: "は = topic",                        aEx: "私はシシルです",   aRo: "watashi wa Shishir desu",       aNe: "म शिशिर हुँ",          b: "が = subject / new info",                bEx: "誰がシシルですか",  bRo: "dare ga Shishir desu ka",        bNe: "को शिशिर हो?" },
          { pair: "に vs で",          a: "に = destination / time",          aEx: "学校に行きます",   aRo: "gakkō ni ikimasu",              aNe: "स्कूल जान्छु",           b: "で = location of action",                 bEx: "学校で勉強します",  bRo: "gakkō de benkyō shimasu",        bNe: "स्कूलमा पढ्छु" },
          { pair: "へ vs に",          a: "へ = direction toward",            aEx: "東京へ行きます",   aRo: "tōkyō e ikimasu",               aNe: "टोकियो तिर जान्छु",     b: "に = arrival point",                      bEx: "東京に着きます",     bRo: "tōkyō ni tsukimasu",             bNe: "टोकियो पुग्छु" },
          { pair: "と vs や",          a: "と = AND (complete list)",         aEx: "りんごとバナナ",   aRo: "ringo to banana",               aNe: "स्याउ र केरा",         b: "や = AND (open / 'and others')",          bEx: "りんごやバナナ",     bRo: "ringo ya banana",                bNe: "स्याउ, केरा, आदि" },
          { pair: "あげる / くれる / もらう", a: "あげる = I give TO others; くれる = others give TO me", aEx: "妹に本をあげました", aRo: "imōto ni hon o agemashita", aNe: "बहिनीलाई किताब दिएँ", b: "もらう = I receive FROM others", bEx: "友達に本をもらいました", bRo: "tomodachi ni hon o moraimashita", bNe: "साथीबाट किताब पाएँ" },
          { pair: "行く vs 来る",      a: "行く = go (away from speaker)",    aEx: "学校に行きます",   aRo: "gakkō ni ikimasu",              aNe: "स्कूल जान्छु",          b: "来る = come (toward speaker)",           bEx: "家に来てください",   bRo: "ie ni kite kudasai",             bNe: "घरमा आउनुहोस्" },
          { pair: "〜ている vs 〜てある", a: "〜ている = ongoing or state",    aEx: "本を読んでいます", aRo: "hon o yonde imasu",             aNe: "किताब पढिरहेको छु",     b: "〜てある = state left BY someone",        bEx: "ドアが開けてあります", bRo: "doa ga akete arimasu",         bNe: "ढोका खुला राखिएको छ" },
          { pair: "上手 vs 得意",      a: "上手 = SKILLED (say of others)",   aEx: "日本語が上手ですね", aRo: "nihongo ga jōzu desu ne",      aNe: "जापानी राम्रो छ है",     b: "得意 = STRONG AT (say of self)",          bEx: "数学が得意です",     bRo: "sūgaku ga tokui desu",           bNe: "गणितमा राम्रो छु" },
          { pair: "から vs ので",      a: "から = because (casual)",         aEx: "寒いから、帰ります", aRo: "samui kara, kaerimasu",       aNe: "जाडो छ, फर्कन्छु",      b: "ので = because (softer, polite)",         bEx: "寒いので、帰ります", bRo: "samui node, kaerimasu",          bNe: "जाडो भएकोले, फर्कन्छु" },
          { pair: "だけ vs しか",      a: "だけ = only (neutral)",            aEx: "水だけ飲みます",   aRo: "mizu dake nomimasu",            aNe: "पानी मात्र पिउँछु",      b: "しか〜ない = only ('not enough')",         bEx: "水しか飲みません",   bRo: "mizu shika nomimasen",           bNe: "पानी बाहेक केहि पिउँदिनँ" },
        ],
      },
      {
        label: "2", title: "Workplace / IT",
        rows: [
          { pair: "は vs が",          a: "は = topic",                        aEx: "私はエンジニアです", aRo: "watashi wa enjinia desu",       aNe: "म इन्जिनियर हुँ",       b: "が = subject / new info",                bEx: "誰がリードですか",  bRo: "dare ga rīdo desu ka",           bNe: "लीड को हो?" },
          { pair: "に vs で",          a: "に = destination",                 aEx: "会議に行きます",   aRo: "kaigi ni ikimasu",              aNe: "बैठकमा जान्छु",        b: "で = location of action",                bEx: "会議室で話します",  bRo: "kaigishitsu de hanashimasu",     bNe: "बैठक कोठामा कुरा गर्छु" },
          { pair: "へ vs に",          a: "へ = direction",                   aEx: "オフィスへ行きます", aRo: "ofisu e ikimasu",               aNe: "अफिस तिर जान्छु",       b: "に = arrival",                            bEx: "オフィスに着きました", bRo: "ofisu ni tsukimashita",       bNe: "अफिस पुगें" },
          { pair: "と vs や",          a: "と = AND (complete)",              aEx: "コードとテスト",   aRo: "kōdo to tesuto",                aNe: "कोड र टेस्ट",          b: "や = AND (open)",                         bEx: "コードやテスト",     bRo: "kōdo ya tesuto",                 bNe: "कोड, टेस्ट, आदि" },
          { pair: "あげる / くれる / もらう", a: "あげる / くれる = give direction", aEx: "上司に資料をあげました", aRo: "jōshi ni shiryō o agemashita", aNe: "बोसलाई कागजात दिएँ",   b: "もらう = receive",                       bEx: "上司から資料をもらいました", bRo: "jōshi kara shiryō o moraimashita", bNe: "बोसबाट कागजात पाएँ" },
          { pair: "行く vs 来る",      a: "行く = go (away)",                 aEx: "会議に行きます",   aRo: "kaigi ni ikimasu",              aNe: "बैठकमा जान्छु",         b: "来る = come (toward)",                    bEx: "私のデスクに来てください", bRo: "watashi no desuku ni kite kudasai", bNe: "मेरो डेस्कमा आउनुहोस्" },
          { pair: "〜ている vs 〜てある", a: "〜ている = ongoing",              aEx: "コードを書いています", aRo: "kōdo o kaite imasu",          aNe: "कोड लेखिरहेको छु",      b: "〜てある = state left BY someone",        bEx: "ファイルが保存してあります", bRo: "fairu ga hozon shite arimasu", bNe: "फाइल सेभ गरिएको छ" },
          { pair: "上手 vs 得意",      a: "上手 = praise others",             aEx: "コードが上手ですね", aRo: "kōdo ga jōzu desu ne",          aNe: "कोडिङ राम्रो छ है",       b: "得意 = self-assess",                      bEx: "Pythonが得意です",   bRo: "Python ga tokui desu",           bNe: "पाइथनमा राम्रो छु" },
          { pair: "から vs ので",      a: "から = casual reason",            aEx: "忙しいから、後で",  aRo: "isogashii kara, ato de",        aNe: "व्यस्त छु, पछि",          b: "ので = polite reason",                    bEx: "会議があるので、後で", bRo: "kaigi ga aru node, ato de",    bNe: "बैठक भएकोले, पछि" },
          { pair: "だけ vs しか",      a: "だけ = only (neutral)",            aEx: "コードだけ書きます", aRo: "kōdo dake kakimasu",            aNe: "कोड मात्र लेख्छु",       b: "しか〜ない = only ('not enough')",         bEx: "1時間しかありません", bRo: "ichi-jikan shika arimasen",     bNe: "१ घण्टा मात्र छ" },
        ],
      },
      {
        label: "3", title: "Restaurant / shopping",
        rows: [
          { pair: "は vs が",          a: "は = topic",                        aEx: "ラーメンはおいしいです", aRo: "rāmen wa oishii desu",         aNe: "रामेन मिठो छ",          b: "が = subject / new info",                bEx: "誰が注文しましたか", bRo: "dare ga chūmon shimashita ka",   bNe: "कसले अर्डर गर्यो?" },
          { pair: "に vs で",          a: "に = arriving at",                 aEx: "店に着きました",    aRo: "mise ni tsukimashita",          aNe: "पसल पुगें",            b: "で = action at",                          bEx: "店で食べます",       bRo: "mise de tabemasu",               bNe: "पसलमा खान्छु" },
          { pair: "へ vs に",          a: "へ = direction",                   aEx: "店へ行きます",      aRo: "mise e ikimasu",                aNe: "पसल तिर जान्छु",        b: "に = arrival",                            bEx: "店に着きます",       bRo: "mise ni tsukimasu",              bNe: "पसल पुग्छु" },
          { pair: "と vs や",          a: "と = AND (complete)",              aEx: "寿司とラーメン",    aRo: "sushi to rāmen",                aNe: "सुसी र रामेन (दुई मात्र)", b: "や = AND (open)",                         bEx: "寿司やラーメン",     bRo: "sushi ya rāmen",                 bNe: "सुसी, रामेन, आदि" },
          { pair: "あげる / くれる / もらう", a: "あげる / くれる",                aEx: "店員にチップをあげました", aRo: "ten'in ni chippu o agemashita", aNe: "कर्मचारीलाई टिप दिएँ", b: "もらう",                                bEx: "サービスをもらいました", bRo: "sābisu o moraimashita",         bNe: "सेवा पाएँ" },
          { pair: "行く vs 来る",      a: "行く = go",                        aEx: "コンビニに行きます", aRo: "konbini ni ikimasu",            aNe: "कन्भिनी जान्छु",         b: "来る = come",                             bEx: "店員が来ます",       bRo: "ten'in ga kimasu",               bNe: "कर्मचारी आउँछ" },
          { pair: "〜ている vs 〜てある", a: "〜ている = ongoing",              aEx: "注文しています",   aRo: "chūmon shite imasu",            aNe: "अर्डर गरिरहेको छु",      b: "〜てある = pre-arranged",                 bEx: "予約してあります",   bRo: "yoyaku shite arimasu",           bNe: "बुक गरिएको छ" },
          { pair: "上手 vs 得意",      a: "上手 = praise",                    aEx: "お料理が上手ですね", aRo: "oryōri ga jōzu desu ne",        aNe: "खाना पकाउन राम्रो है",   b: "得意 = self-claim",                       bEx: "寿司が得意です",     bRo: "sushi ga tokui desu",            bNe: "सुसी बनाउन राम्रो छु" },
          { pair: "から vs ので",      a: "から = casual",                    aEx: "おいしいから、また来ます", aRo: "oishii kara, mata kimasu",   aNe: "मिठो भएकोले, फेरि आउँछु", b: "ので = polite",                          bEx: "美味しいので、また来ます", bRo: "oishii node, mata kimasu",     bNe: "मिठो भएकोले, फेरि आउँछु" },
          { pair: "だけ vs しか",      a: "だけ = only (neutral)",            aEx: "コーヒーだけください", aRo: "kōhī dake kudasai",            aNe: "कफी मात्र दिनुहोस्",      b: "しか〜ない = only ('not enough')",         bEx: "500円しかありません",bRo: "go-hyaku en shika arimasen",     bNe: "५०० येन मात्र छ" },
        ],
      },
      {
        label: "4", title: "Travel / directions",
        rows: [
          { pair: "は vs が",          a: "は = topic",                        aEx: "京都は美しいです",   aRo: "kyōto wa utsukushii desu",      aNe: "क्योटो सुन्दर छ",        b: "が = subject / new info",                bEx: "誰が観光客ですか",   bRo: "dare ga kankōkyaku desu ka",     bNe: "पर्यटक को हो?" },
          { pair: "に vs で",          a: "に = arriving at",                 aEx: "京都に着きます",    aRo: "kyōto ni tsukimasu",            aNe: "क्योटो पुग्छु",         b: "で = location of action",                 bEx: "京都で写真を撮ります", bRo: "kyōto de shashin o torimasu",   bNe: "क्योटोमा फोटो खिच्छु" },
          { pair: "へ vs に",          a: "へ = direction (vague)",           aEx: "京都へ行きます",    aRo: "kyōto e ikimasu",               aNe: "क्योटो तिर जान्छु",      b: "に = arrival (specific)",                  bEx: "京都駅に着きます",   bRo: "kyōto-eki ni tsukimasu",         bNe: "क्योटो स्टेशन पुग्छु" },
          { pair: "と vs や",          a: "と = AND (complete)",              aEx: "京都と奈良",       aRo: "kyōto to nara",                 aNe: "क्योटो र नारा (दुई मात्र)", b: "や = AND (open)",                       bEx: "京都や奈良",         bRo: "kyōto ya nara",                  bNe: "क्योटो, नारा, आदि" },
          { pair: "あげる / くれる / もらう", a: "あげる / くれる",                aEx: "ガイドにチップをあげました", aRo: "gaido ni chippu o agemashita", aNe: "गाइडलाई टिप दिएँ",     b: "もらう",                                bEx: "ガイドから地図をもらいました", bRo: "gaido kara chizu o moraimashita", bNe: "गाइडबाट नक्सा पाएँ" },
          { pair: "行く vs 来る",      a: "行く = go to",                     aEx: "京都に行きます",    aRo: "kyōto ni ikimasu",              aNe: "क्योटो जान्छु",          b: "来る = come to me",                       bEx: "ホテルに来てください", bRo: "hoteru ni kite kudasai",       bNe: "होटेलमा आउनुहोस्" },
          { pair: "〜ている vs 〜てある", a: "〜ている = ongoing",              aEx: "観光しています",   aRo: "kankō shite imasu",             aNe: "घुम्दैछु",              b: "〜てある = arranged",                     bEx: "ホテルが予約してあります", bRo: "hoteru ga yoyaku shite arimasu", bNe: "होटेल बुक गरिएको छ" },
          { pair: "上手 vs 得意",      a: "上手 = praise local",              aEx: "日本語が上手ですね", aRo: "nihongo ga jōzu desu ne",       aNe: "जापानी राम्रो छ है",      b: "得意 = self-claim",                       bEx: "道案内が得意です",   bRo: "michi-annai ga tokui desu",       bNe: "बाटो देखाउनमा राम्रो छु" },
          { pair: "から vs ので",      a: "から = casual",                    aEx: "雨だから、ホテルへ", aRo: "ame da kara, hoteru e",         aNe: "वर्षा भएकोले, होटेल",     b: "ので = polite",                           bEx: "雨ですので、ホテルへ", bRo: "ame desu node, hoteru e",      bNe: "वर्षा भएकोले, होटेल (नम्र)" },
          { pair: "だけ vs しか",      a: "だけ = only (neutral)",            aEx: "京都だけ行きます",  aRo: "kyōto dake ikimasu",            aNe: "क्योटो मात्र जान्छु",     b: "しか〜ない = only ('not enough')",         bEx: "京都しか行けません", bRo: "kyōto shika ikemasen",           bNe: "क्योटो बाहेक जान सक्दिनँ" },
        ],
      },
      {
        label: "5", title: "School / study",
        rows: [
          { pair: "は vs が",          a: "は = topic",                        aEx: "私は学生です",     aRo: "watashi wa gakusei desu",       aNe: "म विद्यार्थी हुँ",       b: "が = subject / new info",                bEx: "誰が先生ですか",     bRo: "dare ga sensei desu ka",         bNe: "शिक्षक को हो?" },
          { pair: "に vs で",          a: "に = destination / time",          aEx: "学校に行きます",   aRo: "gakkō ni ikimasu",              aNe: "स्कूल जान्छु",          b: "で = location of action",                 bEx: "学校で勉強します",  bRo: "gakkō de benkyō shimasu",        bNe: "स्कूलमा पढ्छु" },
          { pair: "へ vs に",          a: "へ = direction",                   aEx: "教室へ行きます",    aRo: "kyōshitsu e ikimasu",           aNe: "कक्षा तिर जान्छु",       b: "に = arrival",                            bEx: "教室に着きます",     bRo: "kyōshitsu ni tsukimasu",         bNe: "कक्षा पुग्छु" },
          { pair: "と vs や",          a: "と = AND (complete)",              aEx: "漢字と文法",       aRo: "kanji to bunpō",                aNe: "कान्जी र व्याकरण",      b: "や = AND (open)",                         bEx: "漢字や文法",         bRo: "kanji ya bunpō",                 bNe: "कान्जी, व्याकरण, आदि" },
          { pair: "あげる / くれる / もらう", a: "あげる / くれる",                aEx: "先生にプレゼントをあげました", aRo: "sensei ni purezento o agemashita", aNe: "शिक्षकलाई उपहार दिएँ", b: "もらう",                            bEx: "先生から本をもらいました", bRo: "sensei kara hon o moraimashita", bNe: "शिक्षकबाट किताब पाएँ" },
          { pair: "行く vs 来る",      a: "行く = go to",                     aEx: "学校に行きます",   aRo: "gakkō ni ikimasu",              aNe: "स्कूल जान्छु",           b: "来る = come to me",                       bEx: "教室に来てください", bRo: "kyōshitsu ni kite kudasai",      bNe: "कक्षामा आउनुहोस्" },
          { pair: "〜ている vs 〜てある", a: "〜ている = ongoing",              aEx: "勉強しています",   aRo: "benkyō shite imasu",            aNe: "पढिरहेको छु",            b: "〜てある = state left BY someone",        bEx: "黒板に書いてあります", bRo: "kokuban ni kaite arimasu",      bNe: "बोर्डमा लेखिएको छ" },
          { pair: "上手 vs 得意",      a: "上手 = praise classmate",          aEx: "発音が上手ですね", aRo: "hatsuon ga jōzu desu ne",       aNe: "उच्चारण राम्रो छ है",    b: "得意 = self-claim",                       bEx: "漢字が得意です",     bRo: "kanji ga tokui desu",            bNe: "कान्जीमा राम्रो छु" },
          { pair: "から vs ので",      a: "から = casual",                    aEx: "難しいから、聞きました", aRo: "muzukashii kara, kikimashita", aNe: "गाह्रो भएकोले, सोधेँ",  b: "ので = polite",                           bEx: "難しいので、教えてください", bRo: "muzukashii node, oshiete kudasai", bNe: "गाह्रो भएकोले, सिकाउनुहोस्" },
          { pair: "だけ vs しか",      a: "だけ = only (neutral)",            aEx: "漢字だけ勉強します", aRo: "kanji dake benkyō shimasu",     aNe: "कान्जी मात्र पढ्छु",     b: "しか〜ない = only ('not enough')",         bEx: "1時間しか勉強しません",bRo: "ichi-jikan shika benkyō shimasen",bNe: "१ घण्टा मात्र पढ्छु" },
        ],
      },
    ],
  },

  // ════════════════════════════════════════════════════════════════
  // COUNTERS — same 12 counters, 5 example contexts
  // ════════════════════════════════════════════════════════════════
  counters: {
    intro: "Same 12 counters, 5 contexts. Each set shows how to count things in that situation. Three of these (つ, 人, 本) cover most of daily life.",
    sets: [
      {
        label: "1", title: "Daily life",
        rows: [
          { c: "〜つ",   cRo: "-tsu",   use: "General things",                          one: "ひとつ",   oneRo: "hitotsu",  two: "ふたつ",  twoRo: "futatsu", three: "みっつ",   threeRo: "mittsu",   ex: "りんごをみっつください",        exRo: "ringo o mittsu kudasai",         exNe: "तीन वटा स्याउ दिनुहोस्",  note: "Goes up to とお (10). Safest fallback." },
          { c: "〜人",   cRo: "-nin",   use: "People",                                  one: "ひとり",   oneRo: "hitori",   two: "ふたり",  twoRo: "futari",  three: "さんにん", threeRo: "san-nin",  ex: "家族は四人です",               exRo: "kazoku wa yo-nin desu",          exNe: "परिवारमा ४ जना छौं",      note: "1 & 2 are irregular (hitori, futari)." },
          { c: "〜本",   cRo: "-hon",   use: "Long cylindrical (pens, bottles)",        one: "いっぽん", oneRo: "ippon",    two: "にほん",  twoRo: "ni-hon",  three: "さんぼん", threeRo: "san-bon",  ex: "ペンを2本ください",            exRo: "pen o ni-hon kudasai",           exNe: "२ वटा कलम दिनुहोस्",      note: "Sound shifts: ippon, sanbon, roppon." },
          { c: "〜枚",   cRo: "-mai",   use: "Flat things (paper, shirts)",             one: "いちまい", oneRo: "ichi-mai", two: "にまい",  twoRo: "ni-mai",  three: "さんまい", threeRo: "san-mai",  ex: "シャツを2枚買いました",        exRo: "shatsu o ni-mai kaimashita",     exNe: "२ वटा सर्ट किनें",        note: "Regular pattern. Use for shirts too." },
          { c: "〜個",   cRo: "-ko",    use: "Small objects (eggs, apples)",            one: "いっこ",   oneRo: "ikko",     two: "にこ",    twoRo: "ni-ko",   three: "さんこ",   threeRo: "san-ko",   ex: "卵を3個ください",              exRo: "tamago o san-ko kudasai",        exNe: "३ वटा अण्डा दिनुहोस्",    note: "Sound shifts on 1, 6, 8, 10." },
          { c: "〜匹",   cRo: "-hiki",  use: "Small animals (cats, dogs)",              one: "いっぴき", oneRo: "ippiki",   two: "にひき",  twoRo: "ni-hiki", three: "さんびき", threeRo: "san-biki", ex: "犬を1匹飼っています",          exRo: "inu o ippiki katte imasu",       exNe: "१ वटा कुकुर पालेको छु",    note: "Large animals use 〜頭. Birds use 〜羽." },
          { c: "〜階",   cRo: "-kai",   use: "Floors of a building",                    one: "いっかい", oneRo: "ikkai",    two: "にかい",  twoRo: "ni-kai",  three: "さんがい", threeRo: "san-gai",  ex: "私の家は2階にあります",        exRo: "watashi no ie wa ni-kai ni arimasu", exNe: "मेरो घर २ तलामा छ",      note: "Same kanji as 〜回 (times)." },
          { c: "〜回",   cRo: "-kai",   use: "Times (occurrences)",                     one: "いっかい", oneRo: "ikkai",    two: "にかい",  twoRo: "ni-kai",  three: "さんかい", threeRo: "san-kai",  ex: "週に三回、運動します",         exRo: "shū ni san-kai, undō shimasu",   exNe: "हप्ताको ३ चोटि व्यायाम",   note: "週に三回 = 3 times a week." },
          { c: "〜歳",   cRo: "-sai",   use: "Age",                                     one: "いっさい", oneRo: "issai",    two: "にさい",  twoRo: "ni-sai",  three: "さんさい", threeRo: "san-sai",  ex: "私は30歳です",                exRo: "watashi wa san-jissai desu",     exNe: "मेरो उमेर ३० वर्ष हो",    note: "20 is special: はたち (hatachi)." },
          { c: "〜時",   cRo: "-ji",    use: "O'clock (hour)",                          one: "いちじ",   oneRo: "ichi-ji",  two: "にじ",    twoRo: "ni-ji",   three: "さんじ",   threeRo: "san-ji",   ex: "今、3時です",                  exRo: "ima, san-ji desu",               exNe: "अहिले ३ बज्यो",          note: "Use 〜分 (fun/pun) for minutes." },
          { c: "〜分",   cRo: "-fun",   use: "Minutes",                                 one: "いっぷん", oneRo: "ippun",    two: "にふん",  twoRo: "ni-fun",  three: "さんぷん", threeRo: "san-pun",  ex: "5分待ってください",           exRo: "go-fun matte kudasai",           exNe: "५ मिनेट कुर्नुहोस्",      note: "Shifts: ippun, sanpun, juppun." },
          { c: "〜冊",   cRo: "-satsu", use: "Bound things (books, magazines)",         one: "いっさつ", oneRo: "issatsu",  two: "にさつ",  twoRo: "ni-satsu", three: "さんさつ", threeRo: "san-satsu",ex: "本を3冊読みました",           exRo: "hon o san-satsu yomimashita",    exNe: "३ वटा किताब पढें",        note: "Books, dictionaries, manga volumes." },
        ],
      },
      {
        label: "2", title: "Workplace / IT",
        rows: [
          { c: "〜つ",   cRo: "-tsu",   use: "General items / tasks",                   one: "ひとつ",   oneRo: "hitotsu",  two: "ふたつ",  twoRo: "futatsu", three: "みっつ",   threeRo: "mittsu",   ex: "タスクが三つあります",        exRo: "tasuku ga mittsu arimasu",       exNe: "३ वटा टास्क छन्",         note: "Counting tasks / tickets generically." },
          { c: "〜人",   cRo: "-nin",   use: "Team members",                            one: "ひとり",   oneRo: "hitori",   two: "ふたり",  twoRo: "futari",  three: "さんにん", threeRo: "san-nin",  ex: "チームは5人です",              exRo: "chīmu wa go-nin desu",           exNe: "टिममा ५ जना छौं",         note: "Counting people in a team / meeting." },
          { c: "〜本",   cRo: "-hon",   use: "Pens, bottles, plans (figuratively)",     one: "いっぽん", oneRo: "ippon",    two: "にほん",  twoRo: "ni-hon",  three: "さんぼん", threeRo: "san-bon",  ex: "プルリクを2本送りました",      exRo: "pururiku o ni-hon okurimashita", exNe: "२ वटा पुल रिक्वेस्ट पठाएँ",note: "Also used informally for PRs / commits." },
          { c: "〜枚",   cRo: "-mai",   use: "Slides, sheets, badges",                  one: "いちまい", oneRo: "ichi-mai", two: "にまい",  twoRo: "ni-mai",  three: "さんまい", threeRo: "san-mai",  ex: "スライドが10枚あります",       exRo: "suraido ga jū-mai arimasu",      exNe: "१० स्लाइड छ",            note: "Presentation slides, ID badges, paper." },
          { c: "〜個",   cRo: "-ko",    use: "Small components / bugs",                 one: "いっこ",   oneRo: "ikko",     two: "にこ",    twoRo: "ni-ko",   three: "さんこ",   threeRo: "san-ko",   ex: "バグを3個直しました",         exRo: "bagu o san-ko naoshimashita",    exNe: "३ वटा बग समाधान गरें",   note: "Small countable things — bugs, items." },
          { c: "〜匹",   cRo: "-hiki",  use: "(rare at work — office pet)",             one: "いっぴき", oneRo: "ippiki",   two: "にひき",  twoRo: "ni-hiki", three: "さんびき", threeRo: "san-biki", ex: "事務所に猫が1匹います",        exRo: "jimusho ni neko ga ippiki imasu", exNe: "अफिसमा १ वटा बिरालो छ",   note: "Most offices don't have pets — rare." },
          { c: "〜階",   cRo: "-kai",   use: "Office floor",                            one: "いっかい", oneRo: "ikkai",    two: "にかい",  twoRo: "ni-kai",  three: "さんがい", threeRo: "san-gai",  ex: "オフィスは5階です",            exRo: "ofisu wa go-kai desu",           exNe: "अफिस ५ औं तलामा छ",       note: "Floor number of the office." },
          { c: "〜回",   cRo: "-kai",   use: "Meetings / standups per week",            one: "いっかい", oneRo: "ikkai",    two: "にかい",  twoRo: "ni-kai",  three: "さんかい", threeRo: "san-kai",  ex: "週に5回、スタンドアップがあります", exRo: "shū ni go-kai, sutandoappu ga arimasu", exNe: "हप्ताको ५ चोटि स्ट्यान्डअप", note: "Recurring meeting counter." },
          { c: "〜歳",   cRo: "-sai",   use: "Age (rarely asked at work)",              one: "いっさい", oneRo: "issai",    two: "にさい",  twoRo: "ni-sai",  three: "さんさい", threeRo: "san-sai",  ex: "彼は35歳です",                exRo: "kare wa san-jū-go-sai desu",     exNe: "उनी ३५ वर्षको हुनुहुन्छ", note: "Bring up only when relevant (birthday)." },
          { c: "〜時",   cRo: "-ji",    use: "Meeting time",                            one: "いちじ",   oneRo: "ichi-ji",  two: "にじ",    twoRo: "ni-ji",   three: "さんじ",   threeRo: "san-ji",   ex: "ミーティングは10時です",       exRo: "mītingu wa jū-ji desu",          exNe: "मीटिङ १० बजे हो",         note: "Specifying meeting hour." },
          { c: "〜分",   cRo: "-fun",   use: "Meeting duration",                        one: "いっぷん", oneRo: "ippun",    two: "にふん",  twoRo: "ni-fun",  three: "さんぷん", threeRo: "san-pun",  ex: "15分の会議です",              exRo: "jū-go-fun no kaigi desu",        exNe: "१५ मिनेटको बैठक हो",      note: "Quick standup or short meeting." },
          { c: "〜冊",   cRo: "-satsu", use: "Tech books / docs",                       one: "いっさつ", oneRo: "issatsu",  two: "にさつ",  twoRo: "ni-satsu", three: "さんさつ", threeRo: "san-satsu",ex: "技術書を5冊買いました",        exRo: "gijutsusho o go-satsu kaimashita", exNe: "५ वटा प्राविधिक किताब किनें", note: "Counting technical books / manuals." },
        ],
      },
      {
        label: "3", title: "Restaurant / shopping",
        rows: [
          { c: "〜つ",   cRo: "-tsu",   use: "Generic orders (set meal, dish)",         one: "ひとつ",   oneRo: "hitotsu",  two: "ふたつ",  twoRo: "futatsu", three: "みっつ",   threeRo: "mittsu",   ex: "ラーメンをひとつください",     exRo: "rāmen o hitotsu kudasai",        exNe: "१ वटा रामेन दिनुहोस्",    note: "Most flexible at restaurants." },
          { c: "〜人",   cRo: "-nin",   use: "Number of diners",                        one: "ひとり",   oneRo: "hitori",   two: "ふたり",  twoRo: "futari",  three: "さんにん", threeRo: "san-nin",  ex: "二人ですけど、空いていますか", exRo: "futari desu kedo, aite imasu ka", exNe: "२ जना छौं, ठाउँ छ?",     note: "Telling host how many in your party." },
          { c: "〜本",   cRo: "-hon",   use: "Bottles / drinks",                        one: "いっぽん", oneRo: "ippon",    two: "にほん",  twoRo: "ni-hon",  three: "さんぼん", threeRo: "san-bon",  ex: "ビールを2本ください",          exRo: "bīru o ni-hon kudasai",          exNe: "२ वटा बियर दिनुहोस्",     note: "Bottles of beer, sake, water." },
          { c: "〜枚",   cRo: "-mai",   use: "Tickets, slices (pizza)",                 one: "いちまい", oneRo: "ichi-mai", two: "にまい",  twoRo: "ni-mai",  three: "さんまい", threeRo: "san-mai",  ex: "ピザを2枚ください",            exRo: "piza o ni-mai kudasai",          exNe: "२ टुक्रा पिज्जा दिनुहोस्",note: "Slices of pizza or flat foods." },
          { c: "〜個",   cRo: "-ko",    use: "Small items (sushi, dumplings)",          one: "いっこ",   oneRo: "ikko",     two: "にこ",    twoRo: "ni-ko",   three: "さんこ",   threeRo: "san-ko",   ex: "餃子を6個ください",            exRo: "gyōza o rok-ko kudasai",         exNe: "६ वटा गियोजा दिनुहोस्",   note: "For sushi pieces, dumplings, etc." },
          { c: "〜匹",   cRo: "-hiki",  use: "Fish / shrimp pieces",                    one: "いっぴき", oneRo: "ippiki",   two: "にひき",  twoRo: "ni-hiki", three: "さんびき", threeRo: "san-biki", ex: "魚を1匹ください",              exRo: "sakana o ippiki kudasai",        exNe: "१ वटा माछा दिनुहोस्",    note: "Whole fish at fishmonger." },
          { c: "〜階",   cRo: "-kai",   use: "Floor of dept store / restaurant",        one: "いっかい", oneRo: "ikkai",    two: "にかい",  twoRo: "ni-kai",  three: "さんがい", threeRo: "san-gai",  ex: "レストランは6階です",          exRo: "resutoran wa rok-kai desu",      exNe: "रेस्टुरेन्ट ६ औं तलामा छ", note: "Common — restaurants in malls." },
          { c: "〜回",   cRo: "-kai",   use: "Visits to shop / restaurant",             one: "いっかい", oneRo: "ikkai",    two: "にかい",  twoRo: "ni-kai",  three: "さんかい", threeRo: "san-kai",  ex: "ここは3回目です",              exRo: "koko wa san-kai-me desu",        exNe: "यो ३ चोटि आएको हो",      note: "Telling staff you're a regular." },
          { c: "〜歳",   cRo: "-sai",   use: "Age for child menu / discount",           one: "いっさい", oneRo: "issai",    two: "にさい",  twoRo: "ni-sai",  three: "さんさい", threeRo: "san-sai",  ex: "子供は5歳です",                exRo: "kodomo wa go-sai desu",          exNe: "बच्चा ५ वर्षको हो",      note: "Used at restaurants with kid pricing." },
          { c: "〜時",   cRo: "-ji",    use: "Closing time",                            one: "いちじ",   oneRo: "ichi-ji",  two: "にじ",    twoRo: "ni-ji",   three: "さんじ",   threeRo: "san-ji",   ex: "10時に閉まります",            exRo: "jū-ji ni shimarimasu",           exNe: "१० बजे बन्द हुन्छ",       note: "Asking / telling closing time." },
          { c: "〜分",   cRo: "-fun",   use: "Wait time",                               one: "いっぷん", oneRo: "ippun",    two: "にふん",  twoRo: "ni-fun",  three: "さんぷん", threeRo: "san-pun",  ex: "20分くらいかかります",         exRo: "ni-jip-pun kurai kakarimasu",    exNe: "करिब २० मिनेट लाग्छ",     note: "How long the food/order will take." },
          { c: "〜冊",   cRo: "-satsu", use: "Menus, recipe books",                     one: "いっさつ", oneRo: "issatsu",  two: "にさつ",  twoRo: "ni-satsu", three: "さんさつ", threeRo: "san-satsu",ex: "メニューを2冊ください",        exRo: "menyū o ni-satsu kudasai",       exNe: "२ वटा मेनु दिनुहोस्",     note: "Some restaurants give multiple menus." },
        ],
      },
      {
        label: "4", title: "Travel / directions",
        rows: [
          { c: "〜つ",   cRo: "-tsu",   use: "Souvenirs / general items",               one: "ひとつ",   oneRo: "hitotsu",  two: "ふたつ",  twoRo: "futatsu", three: "みっつ",   threeRo: "mittsu",   ex: "お土産をふたつ買いました",     exRo: "omiyage o futatsu kaimashita",   exNe: "२ वटा कोसेली किनें",      note: "Bought 2 souvenirs." },
          { c: "〜人",   cRo: "-nin",   use: "Travelers / group size",                  one: "ひとり",   oneRo: "hitori",   two: "ふたり",  twoRo: "futari",  three: "さんにん", threeRo: "san-nin",  ex: "四人で旅行します",            exRo: "yo-nin de ryokō shimasu",        exNe: "४ जना यात्रा गर्छौं",     note: "How many people in your travel group." },
          { c: "〜本",   cRo: "-hon",   use: "Trains, flights, routes",                 one: "いっぽん", oneRo: "ippon",    two: "にほん",  twoRo: "ni-hon",  three: "さんぼん", threeRo: "san-bon",  ex: "電車は1時間に2本です",         exRo: "densha wa ichi-jikan ni ni-hon desu", exNe: "१ घण्टामा २ रेल छ",    note: "Frequency of trains / buses." },
          { c: "〜枚",   cRo: "-mai",   use: "Tickets, postcards",                      one: "いちまい", oneRo: "ichi-mai", two: "にまい",  twoRo: "ni-mai",  three: "さんまい", threeRo: "san-mai",  ex: "切符を2枚ください",            exRo: "kippu o ni-mai kudasai",         exNe: "२ वटा टिकट दिनुहोस्",     note: "Train/movie/concert tickets." },
          { c: "〜個",   cRo: "-ko",    use: "Small bags, items",                       one: "いっこ",   oneRo: "ikko",     two: "にこ",    twoRo: "ni-ko",   three: "さんこ",   threeRo: "san-ko",   ex: "スーツケースを1個持っています", exRo: "sūtsukēsu o ikko motte imasu",  exNe: "१ वटा सुटकेस छ",          note: "Luggage check-in / Airport." },
          { c: "〜匹",   cRo: "-hiki",  use: "Wildlife you spot",                       one: "いっぴき", oneRo: "ippiki",   two: "にひき",  twoRo: "ni-hiki", three: "さんびき", threeRo: "san-biki", ex: "鹿を3匹見ました",              exRo: "shika o san-biki mimashita",     exNe: "३ वटा मृग देखें",        note: "Nara deer, monkeys, fish in pond." },
          { c: "〜階",   cRo: "-kai",   use: "Hotel floor",                             one: "いっかい", oneRo: "ikkai",    two: "にかい",  twoRo: "ni-kai",  three: "さんがい", threeRo: "san-gai",  ex: "部屋は7階です",                exRo: "heya wa nana-kai desu",          exNe: "कोठा ७ औं तलामा छ",       note: "What floor your hotel room is on." },
          { c: "〜回",   cRo: "-kai",   use: "Number of trips",                         one: "いっかい", oneRo: "ikkai",    two: "にかい",  twoRo: "ni-kai",  three: "さんかい", threeRo: "san-kai",  ex: "日本は2回目です",              exRo: "nihon wa ni-kai-me desu",        exNe: "जापान २ चोटि आएको हो",   note: "Telling locals it's your Nth visit." },
          { c: "〜歳",   cRo: "-sai",   use: "Age (kids' admission)",                   one: "いっさい", oneRo: "issai",    two: "にさい",  twoRo: "ni-sai",  three: "さんさい", threeRo: "san-sai",  ex: "子供は8歳です",                exRo: "kodomo wa hassai desu",          exNe: "बच्चा ८ वर्षको हो",       note: "Sometimes asked at attractions." },
          { c: "〜時",   cRo: "-ji",    use: "Train departure / arrival",               one: "いちじ",   oneRo: "ichi-ji",  two: "にじ",    twoRo: "ni-ji",   three: "さんじ",   threeRo: "san-ji",   ex: "新幹線は8時に出ます",          exRo: "shinkansen wa hachi-ji ni demasu", exNe: "बुलेट ट्रेन ८ बजे जान्छ",  note: "Departure / arrival times." },
          { c: "〜分",   cRo: "-fun",   use: "Travel time / wait",                      one: "いっぷん", oneRo: "ippun",    two: "にふん",  twoRo: "ni-fun",  three: "さんぷん", threeRo: "san-pun",  ex: "京都まで30分です",             exRo: "kyōto made san-juppun desu",     exNe: "क्योटोसम्म ३० मिनेट",     note: "How long until destination." },
          { c: "〜冊",   cRo: "-satsu", use: "Travel guides / phrasebooks",             one: "いっさつ", oneRo: "issatsu",  two: "にさつ",  twoRo: "ni-satsu", three: "さんさつ", threeRo: "san-satsu",ex: "ガイドブックを1冊持っています", exRo: "gaidobukku o issatsu motte imasu", exNe: "१ वटा गाइडबुक छ",         note: "Travel guides / books you've packed." },
        ],
      },
      {
        label: "5", title: "School / study",
        rows: [
          { c: "〜つ",   cRo: "-tsu",   use: "Generic study items / chapters",          one: "ひとつ",   oneRo: "hitotsu",  two: "ふたつ",  twoRo: "futatsu", three: "みっつ",   threeRo: "mittsu",   ex: "宿題がみっつあります",        exRo: "shukudai ga mittsu arimasu",     exNe: "३ वटा गृहकार्य छ",        note: "Counting assignments." },
          { c: "〜人",   cRo: "-nin",   use: "Classmates / students",                   one: "ひとり",   oneRo: "hitori",   two: "ふたり",  twoRo: "futari",  three: "さんにん", threeRo: "san-nin",  ex: "クラスは30人です",             exRo: "kurasu wa san-jū-nin desu",      exNe: "कक्षामा ३० जना छौं",      note: "Number of students in a class." },
          { c: "〜本",   cRo: "-hon",   use: "Pens, pencils",                           one: "いっぽん", oneRo: "ippon",    two: "にほん",  twoRo: "ni-hon",  three: "さんぼん", threeRo: "san-bon",  ex: "鉛筆を3本持ってきてください",  exRo: "enpitsu o san-bon motte kite kudasai", exNe: "३ वटा पेन्सिल ल्याउनुहोस्", note: "Asking student to bring pencils." },
          { c: "〜枚",   cRo: "-mai",   use: "Sheets of paper, worksheets",             one: "いちまい", oneRo: "ichi-mai", two: "にまい",  twoRo: "ni-mai",  three: "さんまい", threeRo: "san-mai",  ex: "プリントが3枚あります",        exRo: "purinto ga san-mai arimasu",     exNe: "३ पाना प्रिन्ट छ",        note: "Printouts, worksheets, tests." },
          { c: "〜個",   cRo: "-ko",    use: "Questions on a test",                     one: "いっこ",   oneRo: "ikko",     two: "にこ",    twoRo: "ni-ko",   three: "さんこ",   threeRo: "san-ko",   ex: "問題を5個間違えました",        exRo: "mondai o go-ko machigaemashita", exNe: "५ वटा प्रश्न बिगारेँ",    note: "Number of test questions wrong." },
          { c: "〜匹",   cRo: "-hiki",  use: "School pets / lab animals",               one: "いっぴき", oneRo: "ippiki",   two: "にひき",  twoRo: "ni-hiki", three: "さんびき", threeRo: "san-biki", ex: "教室にうさぎが2匹います",      exRo: "kyōshitsu ni usagi ga ni-hiki imasu", exNe: "कक्षामा २ वटा खरायो छ", note: "Class pets, lab animals." },
          { c: "〜階",   cRo: "-kai",   use: "Classroom / library floor",               one: "いっかい", oneRo: "ikkai",    two: "にかい",  twoRo: "ni-kai",  three: "さんがい", threeRo: "san-gai",  ex: "図書館は3階です",              exRo: "toshokan wa san-gai desu",       exNe: "पुस्तकालय ३ औं तलामा छ",  note: "Locating school facilities." },
          { c: "〜回",   cRo: "-kai",   use: "Times you've taken a test / studied",     one: "いっかい", oneRo: "ikkai",    two: "にかい",  twoRo: "ni-kai",  three: "さんかい", threeRo: "san-kai",  ex: "試験は2回目です",              exRo: "shiken wa ni-kai-me desu",       exNe: "परीक्षा २ चोटि भयो",      note: "Retake counter." },
          { c: "〜歳",   cRo: "-sai",   use: "Age of student",                          one: "いっさい", oneRo: "issai",    two: "にさい",  twoRo: "ni-sai",  three: "さんさい", threeRo: "san-sai",  ex: "息子は12歳です",               exRo: "musuko wa jū-ni-sai desu",       exNe: "छोरा १२ वर्षको हो",       note: "Age of children at school." },
          { c: "〜時",   cRo: "-ji",    use: "Class time / period",                     one: "いちじ",   oneRo: "ichi-ji",  two: "にじ",    twoRo: "ni-ji",   three: "さんじ",   threeRo: "san-ji",   ex: "授業は9時からです",            exRo: "jugyō wa ku-ji kara desu",       exNe: "कक्षा ९ बजेदेखि",         note: "When classes start." },
          { c: "〜分",   cRo: "-fun",   use: "Test duration / break",                   one: "いっぷん", oneRo: "ippun",    two: "にふん",  twoRo: "ni-fun",  three: "さんぷん", threeRo: "san-pun",  ex: "テストは45分です",             exRo: "tesuto wa yon-jū-go-fun desu",   exNe: "टेस्ट ४५ मिनेटको हो",     note: "Length of test or class period." },
          { c: "〜冊",   cRo: "-satsu", use: "Textbooks / notebooks",                   one: "いっさつ", oneRo: "issatsu",  two: "にさつ",  twoRo: "ni-satsu", three: "さんさつ", threeRo: "san-satsu",ex: "教科書を5冊買いました",        exRo: "kyōkasho o go-satsu kaimashita", exNe: "५ वटा पाठ्यपुस्तक किनें",  note: "Textbooks bought for class." },
        ],
      },
    ],
  },
};
