/* Quick Cheat — reference tables for Tenses, Particles, Persons,
   Question words, Confusing pairs, Counters. Globals (CHEAT) read
   by buildCheat() in app.js. */
const CHEAT = {
  tenses: {
    intro: "All major tenses with one regular verb (食べる = to eat) so you can see the pattern. Click any Japanese cell to hear it.",
    rows: [
      { tense: "Present (positive)",  polite: "食べます",        politeRo: "tabemasu",        plain: "食べる",   plainRo: "taberu",     copula: "です",                 copulaRo: "desu",                example: "パンを食べます",          exampleRo: "pan o tabemasu",            ne: "रोटी खान्छु" },
      { tense: "Present (negative)",  polite: "食べません",      politeRo: "tabemasen",      plain: "食べない", plainRo: "tabenai",    copula: "じゃありません",       copulaRo: "ja arimasen",         example: "肉を食べません",          exampleRo: "niku o tabemasen",          ne: "मासु खाँदिनँ" },
      { tense: "Past (positive)",     polite: "食べました",      politeRo: "tabemashita",    plain: "食べた",   plainRo: "tabeta",     copula: "でした",               copulaRo: "deshita",             example: "朝、パンを食べました",    exampleRo: "asa, pan o tabemashita",    ne: "बिहान रोटी खाएँ" },
      { tense: "Past (negative)",     polite: "食べませんでした",politeRo: "tabemasen deshita", plain: "食べなかった", plainRo: "tabenakatta", copula: "じゃありませんでした", copulaRo: "ja arimasen deshita", example: "昨日、肉を食べませんでした", exampleRo: "kinō, niku o tabemasen deshita", ne: "हिजो मासु खाइनँ" },
      { tense: "Te-form (connector)", polite: "食べて",          politeRo: "tabete",          plain: "食べて",   plainRo: "tabete",     copula: "で",                   copulaRo: "de",                  example: "食べて、行きます",        exampleRo: "tabete, ikimasu",           ne: "खाएर जान्छु" },
      { tense: "Tai (want to)",       polite: "食べたいです",    politeRo: "tabetai desu",   plain: "食べたい", plainRo: "tabetai",    copula: "—",                    copulaRo: "",                    example: "すしを食べたいです",      exampleRo: "sushi o tabetai desu",      ne: "सुसी खान मन छ" },
      { tense: "Volitional (let's)",  polite: "食べましょう",    politeRo: "tabemashō",      plain: "食べよう", plainRo: "tabeyō",     copula: "—",                    copulaRo: "",                    example: "一緒に食べましょう",      exampleRo: "issho ni tabemashō",        ne: "सँगै खाऔं" },
      { tense: "Te-iru (-ing/now)",   polite: "食べています",    politeRo: "tabete imasu",   plain: "食べている", plainRo: "tabete iru", copula: "—",                    copulaRo: "",                    example: "今、食べています",        exampleRo: "ima, tabete imasu",         ne: "अहिले खाइरहेको छु" },
      { tense: "Can do (potential)",  polite: "食べられます",    politeRo: "taberaremasu",   plain: "食べられる", plainRo: "taberareru", copula: "—",                    copulaRo: "",                    example: "辛い物が食べられます",    exampleRo: "karai mono ga taberaremasu", ne: "पिरो खान सक्छु" },
    ],
  },

  particles: {
    intro: "Particles attach to the word before them and mark its grammatical role. Mastering 〜10 of these unlocks most sentences.",
    rows: [
      { p: "は", ro: "wa",     role: "Topic marker",         ex: "私は学生です",          exRo: "watashi wa gakusei desu",  exNe: "म विद्यार्थी हुँ",   note: "Sets what we're talking ABOUT. Pronounced 'wa' (not 'ha')." },
      { p: "が", ro: "ga",     role: "Subject / new info",   ex: "猫がいます",            exRo: "neko ga imasu",            exNe: "बिरालो छ",          note: "Marks who DID it or new info. Use after 誰 / 何 (who/what)." },
      { p: "を", ro: "o",      role: "Direct object",        ex: "水を飲みます",          exRo: "mizu o nomimasu",          exNe: "पानी पिउँछु",       note: "Marks WHAT the verb acts on. Pronounced 'o' (not 'wo')." },
      { p: "の", ro: "no",     role: "Possessive / linking", ex: "私の本",                exRo: "watashi no hon",           exNe: "मेरो किताब",        note: "Links nouns: A の B = 'A's B' or 'B of A'." },
      { p: "に", ro: "ni",     role: "Target / time",        ex: "会社に行きます",        exRo: "kaisha ni ikimasu",        exNe: "अफिस जान्छु",       note: "Direction TO somewhere, time AT which something happens, indirect object." },
      { p: "で", ro: "de",     role: "Location of action",   ex: "公園で食べます",        exRo: "kōen de tabemasu",         exNe: "पार्कमा खान्छु",     note: "Where ACTION happens; also means BY/WITH (means: 電車で = by train)." },
      { p: "へ", ro: "e",      role: "Direction",            ex: "東京へ行きます",        exRo: "tōkyō e ikimasu",          exNe: "टोकियो तिर जान्छु",  note: "TOWARD a place. Often interchangeable with に for movement." },
      { p: "と", ro: "to",     role: "With / and",           ex: "友達と話します",        exRo: "tomodachi to hanashimasu", exNe: "साथीसँग कुरा गर्छु",  note: "Joins nouns ('and') OR marks companion ('with')." },
      { p: "や", ro: "ya",     role: "And (non-exhaustive)", ex: "りんごやバナナ",        exRo: "ringo ya banana",          exNe: "स्याउ, केरा, आदि",   note: "'A, B, and other things' — open-ended list." },
      { p: "も", ro: "mo",     role: "Also / too",           ex: "私も学生です",          exRo: "watashi mo gakusei desu",  exNe: "म पनि विद्यार्थी हुँ", note: "Replaces は/が/を to mean 'also', 'too', 'even'." },
      { p: "から", ro: "kara", role: "From / because",       ex: "9時から働きます",       exRo: "ku-ji kara hatarakimasu",  exNe: "९ बजेदेखि काम गर्छु",  note: "Starting point of time/place; also clause-end = 'because'." },
      { p: "まで", ro: "made", role: "Until / up to",        ex: "5時まで",               exRo: "go-ji made",               exNe: "५ बजेसम्म",         note: "End point of time/place." },
      { p: "より", ro: "yori", role: "Than (comparison)",    ex: "犬より猫が好き",        exRo: "inu yori neko ga suki",    exNe: "कुकुर भन्दा बिरालो मन पर्छ", note: "X より Y = 'compared to X, Y'. Yori comes after the LESSER." },
      { p: "か", ro: "ka",     role: "Question marker",      ex: "学生ですか",            exRo: "gakusei desu ka",          exNe: "विद्यार्थी हो?",     note: "Sentence-end = question. Also 'A か B' = 'A or B'." },
      { p: "よ", ro: "yo",     role: "Assertion (emphasis)", ex: "おいしいですよ",        exRo: "oishii desu yo",           exNe: "मीठो छ नि",         note: "Tells the listener something they don't know." },
      { p: "ね", ro: "ne",     role: "Confirmation",         ex: "暑いですね",            exRo: "atsui desu ne",            exNe: "गर्मी छ, होइन र?",   note: "Seeking agreement; like English 'isn't it?' / 'right?'" },
    ],
  },

  persons: {
    intro: "Japanese drops pronouns a LOT when context is clear. Use these mostly to start a conversation or when ambiguous.",
    rows: [
      { person: "1st singular (I)",       casual: "僕 / 俺",        casualRo: "boku / ore",   polite: "私",          politeRo: "watashi",    plural: "私たち",        pluralRo: "watashi-tachi", note: "僕 = young male casual. 俺 = rough male. 私 = neutral/polite (everyone)." },
      { person: "2nd singular (you)",     casual: "君 / お前",      casualRo: "kimi / omae",  polite: "あなた",      politeRo: "anata",      plural: "あなたたち",    pluralRo: "anata-tachi",   note: "Often avoided — use the person's NAME + さん instead. 君/お前 sound rude to strangers." },
      { person: "3rd singular (he)",      casual: "彼",             casualRo: "kare",         polite: "彼",          politeRo: "kare",       plural: "彼ら",          pluralRo: "karera",        note: "Also means 'boyfriend' in context. Prefer name + さん." },
      { person: "3rd singular (she)",     casual: "彼女",           casualRo: "kanojo",       polite: "彼女",        politeRo: "kanojo",     plural: "彼女たち",      pluralRo: "kanojo-tachi",  note: "Also means 'girlfriend'. Same advice — use name + さん." },
      { person: "3rd (this person)",      casual: "この人",         casualRo: "kono hito",    polite: "こちらの方",  politeRo: "kochira no kata", plural: "この人たち",  pluralRo: "kono hito-tachi", note: "Polite/formal = こちら (literally 'this side')." },
      { person: "Honorific suffix",       casual: "—",              casualRo: "",             polite: "〜さん / 〜様",politeRo: "-san / -sama", plural: "—",            pluralRo: "",              note: "Attach to NAME. -san = Mr/Ms (default). -sama = very polite. Never use for yourself." },
      { person: "We (inclusive)",         casual: "僕たち",         casualRo: "boku-tachi",   polite: "私たち",      politeRo: "watashi-tachi", plural: "—",          pluralRo: "",              note: "Same word works as both 'we' and 'us'." },
    ],
  },

  questions: {
    intro: "Question words go in the position the answer would occupy. Most become a full question with か at the end.",
    rows: [
      { q: "何 / なに",    ro: "nani / nan", meaning: "what",    ex: "これは何ですか",          exRo: "kore wa nan desu ka",     exNe: "यो के हो?",         note: "Read 'nan' before counters/copula, 'nani' alone." },
      { q: "誰",          ro: "dare",       meaning: "who",     ex: "あの人は誰ですか",        exRo: "ano hito wa dare desu ka", exNe: "ऊ को हो?",          note: "More polite: どなた (donata)." },
      { q: "どこ",         ro: "doko",       meaning: "where",   ex: "トイレはどこですか",      exRo: "toire wa doko desu ka",    exNe: "शौचालय कहाँ छ?",     note: "どちら is more polite for direction." },
      { q: "いつ",         ro: "itsu",       meaning: "when",    ex: "誕生日はいつですか",      exRo: "tanjōbi wa itsu desu ka",  exNe: "जन्मदिन कहिले हो?",  note: "No particle after いつ in most uses." },
      { q: "どう",         ro: "dō",         meaning: "how",     ex: "味はどうですか",          exRo: "aji wa dō desu ka",        exNe: "स्वाद कस्तो छ?",     note: "Also asks for opinion: '〜はどうですか?'" },
      { q: "なぜ / どうして", ro: "naze / dōshite", meaning: "why", ex: "どうして遅れましたか", exRo: "dōshite okuremashita ka",  exNe: "किन ढिलो भयो?",     note: "なぜ is more formal/written. どうして is everyday." },
      { q: "どれ",         ro: "dore",       meaning: "which (of 3+)", ex: "どれが好きですか", exRo: "dore ga suki desu ka",     exNe: "कुन मन पर्छ?",       note: "Stand-alone. どの+noun = 'which X'." },
      { q: "どの",         ro: "dono",       meaning: "which (+noun)", ex: "どの本ですか",     exRo: "dono hon desu ka",         exNe: "कुन किताब हो?",      note: "Always followed by a noun. どれ stands alone." },
      { q: "いくら",        ro: "ikura",      meaning: "how much (cost)", ex: "これはいくらですか", exRo: "kore wa ikura desu ka", exNe: "यो कति हो?",         note: "Specifically for price/amount." },
      { q: "いくつ",        ro: "ikutsu",     meaning: "how many / how old", ex: "いくつありますか", exRo: "ikutsu arimasu ka",   exNe: "कति वटा छ?",         note: "General counter for 'how many'. Also asks age (polite for kids)." },
      { q: "どのくらい",    ro: "dono kurai", meaning: "how long / how much", ex: "どのくらいかかりますか", exRo: "dono kurai kakarimasu ka", exNe: "कति समय लाग्छ?", note: "Duration, distance, quantity." },
      { q: "何時",         ro: "nan-ji",     meaning: "what time", ex: "今、何時ですか",       exRo: "ima, nan-ji desu ka",      exNe: "अहिले कति बजे हो?",  note: "Use with counters: 何人 (how many people), 何枚 (how many sheets)." },
    ],
  },

  pairs: {
    intro: "The pairs that trip up every beginner. Memorise the contrast — not the rules.",
    rows: [
      { pair: "は vs が",        a: "は = topic (what we're talking about)", aEx: "私はシシルです", aRo: "watashi wa Shishir desu",    aNe: "म शिशिर हुँ (मेरो बारे, म शिशिर हुँ)",
                                  b: "が = subject (new info / answer to 'who?')", bEx: "誰がシシルですか", bRo: "dare ga Shishir desu ka", bNe: "को शिशिर हो? (अज्ञात कुरा सोध्दा)" },
      { pair: "に vs で",        a: "に = destination / point in time / existence",  aEx: "学校に行きます",   aRo: "gakkō ni ikimasu",      aNe: "स्कूल जान्छु (गन्तव्य)",
                                  b: "で = location where ACTION happens",            bEx: "学校で勉強します", bRo: "gakkō de benkyō shimasu", bNe: "स्कूलमा पढ्छु (कार्यस्थल)" },
      { pair: "へ vs に",        a: "へ = direction TOWARD (vague)",                 aEx: "東京へ行きます",   aRo: "tōkyō e ikimasu",       aNe: "टोकियो तिर जान्छु",
                                  b: "に = arrival POINT (specific)",                 bEx: "東京に着きます",   bRo: "tōkyō ni tsukimasu",    bNe: "टोकियोमा पुग्छु" },
      { pair: "と vs や",        a: "と = AND (complete list)",                      aEx: "りんごとバナナ",   aRo: "ringo to banana",       aNe: "स्याउ र केरा (मात्र यिनै)",
                                  b: "や = AND (partial / 'and others')",            bEx: "りんごやバナナ",   bRo: "ringo ya banana",       bNe: "स्याउ, केरा, अरू पनि" },
      { pair: "あげる / くれる / もらう", a: "あげる = I give TO others; くれる = others give TO me", aEx: "妹に本をあげました", aRo: "imōto ni hon o agemashita", aNe: "बहिनीलाई किताब दिएँ",
                                          b: "もらう = I receive FROM others",     bEx: "友達に本をもらいました", bRo: "tomodachi ni hon o moraimashita", bNe: "साथीबाट किताब पाएँ" },
      { pair: "行く vs 来る",    a: "行く = go (away from speaker)",                 aEx: "学校に行きます",   aRo: "gakkō ni ikimasu",      aNe: "स्कूल जान्छु",
                                  b: "来る = come (toward speaker/listener)",        bEx: "家に来てください", bRo: "ie ni kite kudasai",    bNe: "घरमा आउनुहोस्" },
      { pair: "〜ている vs 〜てある", a: "〜ている = ongoing (action verbs) or state (change verbs)", aEx: "本を読んでいます", aRo: "hon o yonde imasu", aNe: "किताब पढिरहेको छु",
                                       b: "〜てある = state left BY someone (transitive)", bEx: "ドアが開けてあります", bRo: "doa ga akete arimasu", bNe: "ढोका खुला राखिएको छ" },
      { pair: "上手 vs 得意",    a: "上手 (jōzu) = SKILLED — usually said about OTHERS, sounds boastful for yourself", aEx: "日本語が上手ですね", aRo: "nihongo ga jōzu desu ne", aNe: "जापानी राम्रो छ है",
                                  b: "得意 (tokui) = STRONG AT — fine to say about yourself",  bEx: "数学が得意です",   bRo: "sūgaku ga tokui desu",  bNe: "गणितमा राम्रो छु" },
      { pair: "から vs ので",    a: "から = because (direct, casual)",                aEx: "寒いから、帰ります", aRo: "samui kara, kaerimasu", aNe: "जाडो भएकोले फर्कन्छु",
                                  b: "ので = because (softer, polite)",               bEx: "寒いので、帰ります", bRo: "samui node, kaerimasu", bNe: "जाडो भएकोले फर्कन्छु (नम्र)" },
      { pair: "だけ vs しか",    a: "だけ = only (neutral)",                          aEx: "水だけ飲みます",     aRo: "mizu dake nomimasu",    aNe: "पानी मात्र पिउँछु",
                                  b: "しか〜ない = only (with implied 'not enough')", bEx: "水しか飲みません",   bRo: "mizu shika nomimasen",  bNe: "पानी बाहेक केहि पिउँदिनँ" },
    ],
  },

  counters: {
    intro: "Japanese counts things with a suffix that matches the object's shape/type. Three of these (つ, 人, 本) cover most of daily life.",
    rows: [
      { c: "〜つ",   cRo: "-tsu",   use: "General things (no specific counter)", one: "ひとつ",   oneRo: "hitotsu", two: "ふたつ",   twoRo: "futatsu", three: "みっつ",   threeRo: "mittsu",   note: "Goes up to とお (10). Safest fallback counter." },
      { c: "〜人",   cRo: "-nin",   use: "People",                                one: "ひとり",   oneRo: "hitori",  two: "ふたり",   twoRo: "futari",  three: "さんにん",  threeRo: "san-nin",  note: "1 & 2 are irregular (hitori, futari). 3+ uses 〜nin." },
      { c: "〜本",   cRo: "-hon",   use: "Long cylindrical (bottles, pens, pencils)", one: "いっぽん", oneRo: "ippon",   two: "にほん",   twoRo: "ni-hon",  three: "さんぼん",  threeRo: "san-bon",  note: "Sound shifts: ippon, sanbon, roppon, hyappon." },
      { c: "〜枚",   cRo: "-mai",   use: "Flat things (paper, tickets, shirts)",  one: "いちまい", oneRo: "ichi-mai", two: "にまい",   twoRo: "ni-mai",  three: "さんまい",  threeRo: "san-mai",  note: "Regular — easy. Use for shirts too." },
      { c: "〜個",   cRo: "-ko",    use: "Small objects (eggs, apples, IT widgets)", one: "いっこ",   oneRo: "ikko",    two: "にこ",     twoRo: "ni-ko",   three: "さんこ",    threeRo: "san-ko",   note: "Tiny sound shift on 1, 6, 8, 10 (ikko, rokko, hakko, jikko)." },
      { c: "〜匹",   cRo: "-hiki",  use: "Small animals (cats, dogs, fish, bugs)", one: "いっぴき", oneRo: "ippiki",  two: "にひき",   twoRo: "ni-hiki", three: "さんびき",  threeRo: "san-biki", note: "Large animals (cows, horses) use 〜頭 (tō)." },
      { c: "〜階",   cRo: "-kai",   use: "Floors of a building",                  one: "いっかい", oneRo: "ikkai",   two: "にかい",   twoRo: "ni-kai",  three: "さんがい",  threeRo: "san-gai",  note: "Same kanji as 〜回 (times) — context distinguishes." },
      { c: "〜回",   cRo: "-kai",   use: "Times (occurrences)",                   one: "いっかい", oneRo: "ikkai",   two: "にかい",   twoRo: "ni-kai",  three: "さんかい",  threeRo: "san-kai",  note: "週に三回 = '3 times a week'." },
      { c: "〜歳",   cRo: "-sai",   use: "Age in years",                          one: "いっさい", oneRo: "issai",   two: "にさい",   twoRo: "ni-sai",  three: "さんさい",  threeRo: "san-sai",  note: "20 is special: はたち (hatachi)." },
      { c: "〜時",   cRo: "-ji",    use: "O'clock (hour)",                        one: "いちじ",   oneRo: "ichi-ji", two: "にじ",     twoRo: "ni-ji",   three: "さんじ",    threeRo: "san-ji",   note: "Use 〜分 (fun/pun) for minutes." },
      { c: "〜分",   cRo: "-fun",   use: "Minutes",                               one: "いっぷん", oneRo: "ippun",   two: "にふん",   twoRo: "ni-fun",  three: "さんぷん",  threeRo: "san-pun",  note: "Sound shifts: ippun, sanpun, yonpun, roppun, juppun." },
      { c: "〜冊",   cRo: "-satsu", use: "Bound things (books, magazines)",       one: "いっさつ", oneRo: "issatsu", two: "にさつ",   twoRo: "ni-satsu",three: "さんさつ",  threeRo: "san-satsu",note: "Notebooks, dictionaries, manga volumes." },
    ],
  },
};
